DO $$
DECLARE v_course_id UUID;
BEGIN
SELECT id INTO v_course_id FROM courses WHERE code = 'CIT292' LIMIT 1;

-- Fill-in-the-blank questions (30 questions)

INSERT INTO questions (course_id, question_text, question_type, correct_answer, explanation) VALUES
(v_course_id, 'Our world is an ________ world.', 'fill_in_blank', 'analog', 'Measurements of physical objects are continuous, not discrete.'),
(v_course_id, 'A single 0 or a single 1 is a binary digit or ________.', 'fill_in_blank', 'bit', 'A bit represents the smallest unit of binary data.'),
(v_course_id, 'BCD is the acronym for ________.', 'fill_in_blank', 'Binary Coded Decimal', 'BCD encodes each decimal digit with its binary equivalent.'),
(v_course_id, 'In a Boolean function, the ________ operator is denoted with a dot (.) or no symbol at all.', 'fill_in_blank', 'AND', 'AND operation is represented by multiplication or concatenation.'),
(v_course_id, 'The NOT operator is also known as the ________.', 'fill_in_blank', 'INVERTER', 'NOT gate inverts the input signal.'),
(v_course_id, '________ developed a system of mathematical logic called Boolean algebra in 1854.', 'fill_in_blank', 'George Boole', 'George Boole is the founder of Boolean algebra.'),
(v_course_id, 'In ________, Claude Shannon showed that circuits built with binary switches can be described using Boolean algebra.', 'fill_in_blank', '1938', 'Claude Shannon''s 1938 thesis connected Boolean algebra to switching circuits.'),
(v_course_id, 'The ________ states that if a Boolean expression is true, then its dual is also true.', 'fill_in_blank', 'duality principle', 'The duality principle is fundamental in Boolean algebra.'),
(v_course_id, 'A ________ is a product term that contains all the variables used in a function.', 'fill_in_blank', 'Minterm', 'A minterm includes every variable exactly once.'),
(v_course_id, 'A ________ is a sum term that contains all the variables used in the function.', 'fill_in_blank', 'Maxterm', 'A maxterm includes every variable exactly once in complemented or uncomplemented form.'),
(v_course_id, 'The NOT gate is also called the ________.', 'fill_in_blank', 'INVERTER', 'The NOT gate inverts the input signal.'),
(v_course_id, '________ circuits are the class of digital circuits where the outputs depend only on current inputs.', 'fill_in_blank', 'Combinational', 'Combinational circuits have no memory elements.'),
(v_course_id, '________ are circuits whose outputs depend on current inputs and all past inputs.', 'fill_in_blank', 'Sequential circuits', 'Sequential circuits have memory and feedback.'),
(v_course_id, 'The simplest memory circuit is called a ________.', 'fill_in_blank', 'bistable element', 'Two inverters connected in series form a bistable element.'),
(v_course_id, 'When two 1''s are fed back to the inputs producing 0 at outputs, this behavior is called the ________.', 'fill_in_blank', 'critical race', 'Critical race is an undesirable oscillating condition.'),
(v_course_id, 'The D latch with enable circuit is often referred to as a ________ latch.', 'fill_in_blank', 'transparent', 'Output follows input when enabled (transparent mode).'),
(v_course_id, 'There are basically ________ main types of flip-flops.', 'fill_in_blank', 'four', 'The four types are D, S-R, J-K, and T flip-flops.'),
(v_course_id, 'The most important memory element is the ________.', 'fill_in_blank', 'flip-flop', 'Flip-flops are edge-triggered memory elements.'),
(v_course_id, 'The universal measuring instrument used extensively in computer laboratory is the ________.', 'fill_in_blank', 'Cathode Ray Oscilloscope', 'CRO is used to observe electronic signals.'),
(v_course_id, 'The Quine-McCluskey or ________ method for reducing an equation is ideal for computer programming.', 'fill_in_blank', 'tabulation', 'Tabulation method is algorithmic and computer-friendly.'),
(v_course_id, 'A ________ is a prime implicant that includes a 1-minterm not included in any other prime implicant.', 'fill_in_blank', 'essential prime implicant', 'Essential prime implicants must be included in the minimal expression.'),
(v_course_id, 'To convert a binary number to octal, group bits into groups of ________.', 'fill_in_blank', 'threes', 'Three bits correspond to one octal digit.'),
(v_course_id, 'Hexadecimal numbers use base-________.', 'fill_in_blank', '16', 'Hexadecimal uses 16 digits (0-9, A-F).'),
(v_course_id, 'Octal numbers only use digits from 0 to ________.', 'fill_in_blank', '7', 'Octal is base-8, digits 0 through 7.'),
(v_course_id, 'The binary switch has ________ connections: input, output, and control.', 'fill_in_blank', 'three', 'A binary switch has three terminals.'),
(v_course_id, 'The action of clearing a Flip-Flop is also called ________.', 'fill_in_blank', 'resetting', 'Clearing sets the output to 0 (reset state).'),
(v_course_id, 'The T in T flip-flop stands for ________.', 'fill_in_blank', 'Toggle', 'T flip-flop toggles its output when T=1 and clock edge occurs.'),
(v_course_id, 'A CLEAR input can also be called ________ input.', 'fill_in_blank', 'RESET', 'Clear and reset are synonymous.'),
(v_course_id, 'In a ________ counter, each flip-flop is triggered by the previous flip-flop, causing a ripple effect.', 'fill_in_blank', 'asynchronous', 'Asynchronous counters have propagation delays that accumulate.'),
(v_course_id, 'A ________ changes state only at the active edge of its enable signal.', 'fill_in_blank', 'flip-flop', 'Flip-flops are edge-triggered, unlike level-sensitive latches.');

-- Multiple choice questions (170 questions)

INSERT INTO questions (course_id, question_text, question_type, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(v_course_id, 'A string of n bits can represent how many different pieces of information?', 'multiple_choice', 'n', '2n', '2^n', 'n^2', 'C', 'A string of n bits can represent 2^n different combinations.'),
(v_course_id, 'The decimal digit 4 has a greater value than digit 8 because:', 'multiple_choice', '4 is larger than 8', '4 is in the tenth position while 8 is in the unit position', '8 is even', '4 comes before 8', 'B', 'Positional value matters; 4 in tens place equals 40, exceeding 8 in units place.'),
(v_course_id, 'Which of the following is NOT a basic logic gate?', 'multiple_choice', 'AND', 'OR', 'NOT', 'NAND', 'D', 'NAND is derived from AND and NOT; the three basic gates are AND, OR, NOT.'),
(v_course_id, 'What is the decimal equivalent of binary 1010?', 'multiple_choice', '8', '9', '10', '11', 'C', '1×8 + 0×4 + 1×2 + 0×1 = 8+2 = 10.'),
(v_course_id, 'Which gate outputs HIGH only when all inputs are HIGH?', 'multiple_choice', 'OR', 'AND', 'NOR', 'XOR', 'B', 'AND gate requires all inputs HIGH for output HIGH.'),
(v_course_id, 'Which gate outputs HIGH when at least one input is HIGH?', 'multiple_choice', 'AND', 'NOR', 'OR', 'NAND', 'C', 'OR gate outputs HIGH if any input is HIGH.'),
(v_course_id, 'DeMorgan''s theorem states that (x·y)′ = ?', 'multiple_choice', 'x′ + y′', 'x′·y′', 'x + y', 'x·y', 'A', 'DeMorgan''s first law: complement of AND equals OR of complements.'),
(v_course_id, 'DeMorgan''s theorem states that (x+y)′ = ?', 'multiple_choice', 'x′ + y′', 'x′·y′', 'x + y', 'x·y', 'B', 'DeMorgan''s second law: complement of OR equals AND of complements.'),
(v_course_id, 'What is the octal equivalent of binary 111 010?', 'multiple_choice', '62', '72', '70', '65', 'B', '111=7, 010=2 → 72 in octal.'),
(v_course_id, 'The hexadecimal digit A represents what decimal value?', 'multiple_choice', '9', '10', '11', '12', 'B', 'A = 10 in decimal.'),
(v_course_id, 'Which flip-flop eliminates the indeterminate condition of the S-R flip-flop?', 'multiple_choice', 'T flip-flop', 'D flip-flop', 'J-K flip-flop', 'R-S flip-flop', 'C', 'J-K flip-flop has toggling mode when J=K=1, no indeterminate state.'),
(v_course_id, 'In a K-map, a pair of adjacent 1s represents elimination of how many variables?', 'multiple_choice', '0', '1', '2', '3', 'B', 'A 1-subcube (two adjacent minterms) eliminates one variable.'),
(v_course_id, 'A 4-variable K-map has how many cells?', 'multiple_choice', '4', '8', '16', '32', 'C', '4-variable K-map has 2^4 = 16 cells.'),
(v_course_id, 'What is the main advantage of synchronous counters over asynchronous counters?', 'multiple_choice', 'Lower cost', 'Higher speed', 'Simplicity', 'Uses fewer flip-flops', 'B', 'Synchronous counters operate faster because no accumulated propagation delay.'),
(v_course_id, 'Which gate is known as a coincidence detector?', 'multiple_choice', 'OR gate', 'AND gate', 'NAND gate', 'XOR gate', 'B', 'AND gate outputs HIGH only when all inputs coincide as HIGH.'),
(v_course_id, 'The output of an EX-NOR gate is 1 when:', 'multiple_choice', 'inputs are different', 'inputs are same', 'at least one input is 1', 'both inputs are 0 only', 'B', 'EX-NOR outputs 1 when both inputs are equal (both 0 or both 1).'),
(v_course_id, 'Which of the following is a universal gate?', 'multiple_choice', 'AND', 'OR', 'NOT', 'NAND', 'D', 'NAND gate can be used to create AND, OR, and NOT functions.'),
(v_course_id, 'A half adder adds:', 'multiple_choice', 'two bits and carry-in', 'two bits only', 'three bits', 'one bit only', 'B', 'Half adder adds two single bits, producing sum and carry-out.'),
(v_course_id, 'A full adder adds:', 'multiple_choice', 'two bits only', 'three bits (two operands plus carry-in)', 'four bits', 'one bit only', 'B', 'Full adder adds two bits and a carry-in from previous stage.'),
(v_course_id, 'What does PLD stand for?', 'multiple_choice', 'Programmable Logic Device', 'Power Logic Device', 'Primary Logic Diagram', 'Parallel Logic Driver', 'A', 'PLDs are ICs that can be programmed to execute complex logic functions.'),
(v_course_id, 'Which of the following is NOT a type of counter mentioned?', 'multiple_choice', 'Ring counter', 'Gray-code counter', 'Binary counter', 'Decimal counter', 'D', 'Binary, ring, and gray-code counters are mentioned; decimal is not listed.'),
(v_course_id, 'The MOD number of a counter equals:', 'multiple_choice', 'number of flip-flops', 'number of states before recycling', 'clock frequency', 'output voltage', 'B', 'MOD is the number of distinct states in one complete cycle.'),
(v_course_id, 'What is the simplest counter to build?', 'multiple_choice', 'Synchronous counter', 'Ring counter', 'Ripple counter', 'Gray-code counter', 'C', 'Ripple/asynchronous counters are simplest due to cascaded structure.'),
(v_course_id, 'Which flip-flop is NOT level-sensitive?', 'multiple_choice', 'Latch', 'D latch', 'SR latch', 'Flip-flop', 'D', 'Flip-flops are edge-triggered, latches are level-sensitive.'),
(v_course_id, 'What is the characteristic equation of an SR latch?', 'multiple_choice', 'Q(n+1)=S+RQ(n)', 'Q(n+1)=S+R''Q(n)', 'Q(n+1)=S''+RQ(n)', 'Q(n+1)=S+Q(n)', 'B', 'The characteristic equation is Q(n+1) = (S + Q(n))R''.'),
(v_course_id, 'Which logic family has military grade with wider supply voltage range?', 'multiple_choice', '7400 series', '5400 series', '4000 series', '74LS series', 'B', '5400 series are military grade, 7400 series are commercial.'),
(v_course_id, 'How many full adders are needed for an m-bit parallel adder?', 'multiple_choice', 'm', 'm-1', 'm+1', '2m', 'A', 'An m-bit parallel adder requires m full adders (or one half adder and m-1 full adders).'),
(v_course_id, 'Which gate output is 1 if inputs are different?', 'multiple_choice', 'AND', 'OR', 'XOR', 'XNOR', 'C', 'XOR (exclusive OR) outputs 1 when inputs differ.'),
(v_course_id, 'What does IEEE stand for?', 'multiple_choice', 'Institute of Electrical and Electronics Engineers', 'International Electrical and Electronic Engineers', 'Institute of Energy and Electronic Engineering', 'International Energy and Electrical Engineers', 'A', 'IEEE is the Institute of Electrical and Electronics Engineers.'),
(v_course_id, 'What is the hexadecimal equivalent of decimal 170?', 'multiple_choice', 'A0', 'AA', 'AB', 'A1', 'B', '170 ÷ 16 = 10 remainder 10 → AA (A=10).'),
(v_course_id, 'Convert hex 1E2 to decimal:', 'multiple_choice', '480', '482', '484', '486', 'B', '1×256 + 14×16 + 2 = 256 + 224 + 2 = 482.'),
(v_course_id, 'The octal equivalent of decimal 417 is:', 'multiple_choice', '641', '640', '642', '631', 'A', '417 ÷ 8 = 52 r1, 52 ÷ 8 = 6 r4, 6 ÷ 8 = 0 r6 → 641 octal.'),
(v_course_id, 'How many minterms exist for 3 variables?', 'multiple_choice', '4', '6', '8', '16', 'C', '2^3 = 8 minterms for 3 variables.'),
(v_course_id, 'A 3-variable K-map has how many cells?', 'multiple_choice', '4', '8', '16', '9', 'B', '3-variable K-map has 2^3 = 8 cells.'),
(v_course_id, 'Which gate can be constructed by AND, OR, and NOT gates?', 'multiple_choice', 'NAND only', 'NOR only', 'All gates', 'XOR only', 'C', 'AND, OR, NOT are universal; any gate can be constructed from them.'),
(v_course_id, 'What is the main disadvantage of asynchronous counters?', 'multiple_choice', 'High power consumption', 'Propagation delay accumulation', 'Complex design', 'Limited count range', 'B', 'Ripple effect causes false outputs due to accumulated delays.'),
(v_course_id, 'A bistable element has how many stable states?', 'multiple_choice', 'One', 'Two', 'Three', 'Four', 'B', 'Bistable means two stable states (0 and 1).'),
(v_course_id, 'What is the major advantage of synchronous counters over asynchronous?', 'multiple_choice', 'Higher speed operation', 'Lower cost', 'Fewer gates', 'Easier to design', 'A', 'Synchronous counters operate faster with no ripple delay accumulation.'),
(v_course_id, 'The NAND gate is derived from AND gate and:', 'multiple_choice', 'OR gate', 'NOT gate in series', 'XOR gate', 'Buffer', 'B', 'NAND = AND followed by NOT (inverter).'),
(v_course_id, 'Which flip-flop type has a toggling operation when both inputs are 1?', 'multiple_choice', 'D flip-flop', 'T flip-flop', 'J-K flip-flop', 'SR flip-flop', 'C', 'J-K flip-flop toggles when J=K=1.'),
(v_course_id, 'What does GAL stand for?', 'multiple_choice', 'General Array Logic', 'Generic Array Logic', 'Gate Array Logic', 'Global Array Logic', 'B', 'GAL is Generic Array Logic, a type of programmable logic device.'),
(v_course_id, 'The AND operation can be described as Boolean:', 'multiple_choice', 'Addition', 'Multiplication', 'Subtraction', 'Division', 'B', 'AND corresponds to multiplication in Boolean algebra.'),
(v_course_id, 'The OR operation can be described as Boolean:', 'multiple_choice', 'Addition', 'Multiplication', 'Subtraction', 'Division', 'A', 'OR corresponds to addition in Boolean algebra.'),
(v_course_id, 'Which logic gate is most universally used?', 'multiple_choice', 'AND', 'OR', 'NOT', 'NAND', 'D', 'NAND is universal and widely used in IC design.'),
(v_course_id, 'A single latch can store how many bits?', 'multiple_choice', 'One', 'Two', 'Four', 'Eight', 'A', 'A single latch stores exactly 1 bit of information.'),
(v_course_id, 'Which of the following is level-sensitive?', 'multiple_choice', 'Flip-flop', 'Latch', 'Register', 'Counter', 'B', 'Latches are level-sensitive; flip-flops are edge-triggered.'),
(v_course_id, 'What is the binary equivalent of decimal 15?', 'multiple_choice', '1110', '1111', '1101', '1010', 'B', '8+4+2+1 = 15, binary 1111.'),
(v_course_id, 'What is the binary equivalent of octal 17?', 'multiple_choice', '1111', '1110', '1010', '1101', 'A', 'Octal 1 = 001, 7 = 111 → binary 001111 = 1111.'),
(v_course_id, 'What is the primary difference between 5400 and 7400 series ICs?', 'multiple_choice', 'Pin count differs', '5400 series is military grade with wider voltage/temperature range', '7400 series is faster', '5400 series uses more power', 'B', '5400 series military grade, 7400 commercial grade.'),
(v_course_id, 'What is the expression for AND gate output?', 'multiple_choice', 'A+B', 'A·B', 'A⊕B', 'A′+B′', 'B', 'AND output is A multiplied by B (A·B).'),
(v_course_id, 'Which of the following cannot be a Boolean variable value?', 'multiple_choice', '0', '1', '2', 'Both 0 and 1', 'C', 'Boolean variables are binary, only 0 or 1.'),
(v_course_id, 'A product term containing all variables is a:', 'multiple_choice', 'Maxterm', 'Minterm', 'Sum term', 'Literal', 'B', 'Minterm is a product term with all variables.'),
(v_course_id, 'A sum term containing all variables is a:', 'multiple_choice', 'Minterm', 'Maxterm', 'Product term', 'Literal', 'B', 'Maxterm is a sum term with all variables.'),
(v_course_id, 'Canonical form expresses a function as:', 'multiple_choice', 'sum of minterms or product of maxterms', 'product of minterms', 'sum of maxterms', 'any random form', 'A', 'Canonical form is either sum of minterms or product of maxterms.'),
(v_course_id, 'What is the dual of expression x·y′ + z?', 'multiple_choice', 'x′+y·z′', 'x+y′·z', '(x+y′)·z', 'x·(y′+z)', 'B', 'Duality swaps + with · and 0 with 1.'),
(v_course_id, 'Which theorem states (x·y)′ = x′+y′?', 'multiple_choice', 'DeMorgan''s theorem', 'Duality principle', 'Absorption theorem', 'Idempotent theorem', 'A', 'DeMorgan''s theorem defines complement of AND/OR operations.'),
(v_course_id, 'A Karnaugh map is a graphical representation of:', 'multiple_choice', 'Boolean function', 'Circuit diagram', 'Truth table', 'Both A and C', 'D', 'K-map represents truth table graphically and helps simplify Boolean functions.'),
(v_course_id, 'To interface TTL to CMOS, what is required?', 'multiple_choice', 'Pull-down resistor', 'Pull-up resistor to Vcc', 'Direct connection', 'Buffer gate only', 'B', 'A pull-up resistor between TTL output and Vcc is needed.'),
(v_course_id, 'Low-power Schottky TTL uses less power because:', 'multiple_choice', 'Lower voltage', 'Larger value resistor', 'Fewer transistors', 'Smaller die size', 'B', 'Larger resistor values limit current, reducing power consumption.'),
(v_course_id, 'An OR gate can be imagined as:', 'multiple_choice', 'Switches in series', 'Switches in parallel', 'Switches in series-parallel', 'A single switch', 'B', 'Parallel switches correspond to OR logic.'),
(v_course_id, 'What is propagation time?', 'multiple_choice', 'Time for signal to travel', 'Time for gate to change state', 'Clock period', 'Setup time', 'B', 'Propagation delay is time for output to change after input changes.'),
(v_course_id, 'Which statement about the SR latch is correct?', 'multiple_choice', 'Works when both inputs are 0', 'Works when both inputs are 1', 'Has indeterminate condition when both inputs 1', 'Never has indeterminate condition', 'C', 'SR latch has invalid/indeterminate state when S=1,R=1.'),
(v_course_id, 'The output of SR latch consists of:', 'multiple_choice', 'Q only', 'Q and Q′ (complement)', 'Q and clock', 'Only complement', 'B', 'SR latch has normal output Q and complementary output Q''.'),
(v_course_id, 'How many inputs does an SR latch have?', 'multiple_choice', '1', '2', '3', '4', 'B', 'SR latch has Set and Reset inputs (2 inputs).'),
(v_course_id, 'Which of the following is NOT a type of flip-flop?', 'multiple_choice', 'D flip-flop', 'S-R flip-flop', 'J-K flip-flop', 'X-Y flip-flop', 'D', 'D, S-R, J-K, and T are the four main types.'),
(v_course_id, 'What does the clock signal typically look like?', 'multiple_choice', 'Sine wave', 'Triangular wave', 'Rectangular pulse train', 'Spike', 'C', 'Clock signals are rectangular/square waves.'),
(v_course_id, 'Positive-going transition (PGT) occurs when clock goes:', 'multiple_choice', '1 to 0', '0 to 1', 'X to Z', 'Z to X', 'B', 'PGT is rising edge (0 to 1 transition).'),
(v_course_id, 'Negative-going transition (NGT) occurs when clock goes:', 'multiple_choice', '1 to 0', '0 to 1', 'X to Z', 'Z to X', 'A', 'NGT is falling edge (1 to 0 transition).'),
(v_course_id, 'Most digital systems are principally:', 'multiple_choice', 'Asynchronous', 'Synchronous', 'Combinational', 'Analog', 'B', 'Most digital systems use synchronous design with a clock.'),
(v_course_id, 'A master-slave flip-flop consists of:', 'multiple_choice', 'One flip-flop', 'Two flip-flops (master and slave)', 'Three flip-flops', 'Four latches', 'B', 'Master-slave uses master and slave stages.'),
(v_course_id, 'What is a ripple counter?', 'multiple_choice', 'Each flip-flop clocked by previous output', 'All flip-flops clocked together', 'Counter with no propagation delay', 'Counter with gray code output', 'A', 'Ripple/asynchronous counters have cascaded clocking causing ripple effect.'),
(v_course_id, 'A BCD counter counts from:', 'multiple_choice', '0 to 15', '0 to 9 then recycles', '0 to 7', '1 to 10', 'B', 'BCD counter counts 0 through 9 (decimal digits).'),
(v_course_id, 'Down counters are:', 'multiple_choice', 'More common than up counters', 'Less common than up counters', 'Equally common', 'Never used', 'B', 'Down counters are not as widely used as up counters.'),
(v_course_id, 'A synchronous counter''s propagation delay is approximately:', 'multiple_choice', 'One flip-flop delay plus gate delay', 'Sum of all flip-flop delays', 'Clock period', 'Zero', 'A', 'Delay is one flip-flop toggle time plus AND gate delay.'),
(v_course_id, 'An n-bit binary counter has states from 0 to:', 'multiple_choice', 'n', '2n', '2^n - 1', '2^n', 'C', 'n-bit binary counter counts 0 to 2^n - 1 (total 2^n states).'),
(v_course_id, 'To count 1000 items, how many flip-flops are needed?', 'multiple_choice', '8', '9', '10', '11', 'C', '2^9 = 512, 2^10 = 1024 → need 10 flip-flops.'),
(v_course_id, 'An n-bit binary counter repeats every:', 'multiple_choice', 'n clock pulses', '2n clock pulses', '2^n clock pulses', 'n^2 clock pulses', 'C', 'Complete cycle requires 2^n clock pulses.'),
(v_course_id, 'Which flip-flop is best for counter design where toggling is required?', 'multiple_choice', 'D flip-flop', 'T flip-flop', 'SR flip-flop', 'JK flip-flop with tied inputs', 'D', 'JK with J=K=1 toggles, also T flip-flop is purpose-built for toggling.'),
(v_course_id, 'For battery-operated digital watches, the basic frequency comes from:', 'multiple_choice', 'AC power line', 'Quartz-crystal oscillator', 'RC circuit', 'LC tank', 'B', 'Quartz crystals provide stable, accurate frequency.'),
(v_course_id, 'Digital clocks from AC power line use what frequency?', 'multiple_choice', '60 Hz only', '50 Hz', 'Either 50 or 60 Hz depending on region', '100 Hz', 'C', 'AC line frequency is 50 Hz (Europe/Asia) or 60 Hz (Americas).'),
(v_course_id, 'In a parallel counter, flip-flops change state:', 'multiple_choice', 'Sequentially', 'Simultaneously', 'Randomly', 'Only on negative edge', 'B', 'Parallel/synchronous counters have simultaneous state changes.'),
(v_course_id, 'Which statement about asynchronous counters is FALSE?', 'multiple_choice', 'Propagation delays add up', 'False outputs may occur', 'Fastest counter type', 'Simple to build', 'C', 'Asynchronous counters are slowest due to accumulated delays.'),
(v_course_id, 'A ring counter starts with:', 'multiple_choice', 'All zeros', 'All ones', 'String of 0 bits followed by one 1-bit', 'Alternating bits', 'C', 'Ring counter typically has a single 1 shifting through zeros.'),
(v_course_id, 'Gray-code counter has consecutive values differing in:', 'multiple_choice', 'All bits', 'One bit only', 'Two bits', 'No bits', 'B', 'Gray code ensures adjacent values differ in exactly one bit.'),
(v_course_id, 'What is a prime implicant?', 'multiple_choice', 'Any product term', 'Subcube not contained in any larger subcube', 'Essential term', 'Don''t care term', 'B', 'Prime implicant is a maximal subcube not contained in another subcube.'),
(v_course_id, 'What is the result of x·x + y?', 'multiple_choice', 'x', 'y', 'x+y', '1', 'C', 'x·x = x, so x + y.'),
(v_course_id, 'Which of the following is FALSE about octal numbers?', 'multiple_choice', 'Use digits 0-7', 'Base-8 system', 'Use digits 0-8', 'Group binary in threes', 'C', 'Octal uses digits 0-7 only, not 8.'),
(v_course_id, 'Two switches in series give rise to which logical operator?', 'multiple_choice', 'OR', 'AND', 'NOT', 'XOR', 'B', 'Series connection implements AND logic.'),
(v_course_id, 'Two switches in parallel give rise to which logical operator?', 'multiple_choice', 'AND', 'OR', 'NOT', 'NAND', 'B', 'Parallel connection implements OR logic.'),
(v_course_id, 'A binary switch has how many connections?', 'multiple_choice', 'One', 'Two', 'Three', 'Four', 'C', 'Binary switch has input, output, and control (3 connections).'),
(v_course_id, 'A truth table is a(n):', 'multiple_choice', 'One-dimensional array', 'Two-dimensional array', 'Graph', 'Equation', 'B', 'Truth tables have rows and columns (inputs and outputs).'),
(v_course_id, 'Boolean algebra is a tool for:', 'multiple_choice', 'Digital system analysis and design', 'Analog circuit design', 'Power systems', 'Mechanical engineering', 'A', 'Boolean algebra is fundamental to digital logic design.'),
(v_course_id, 'Boolean theorems help to:', 'multiple_choice', 'Complicate logic', 'Simplify logic expressions and circuits', 'Convert to analog', 'Increase power consumption', 'B', 'Theorems minimize logic for simpler, cheaper circuits.'),
(v_course_id, 'What is the inverse of function F denoted by?', 'multiple_choice', 'F+', 'F-', 'F′ or ¬F', 'F*', 'C', 'Prime notation or overbar denotes complement/inverse.'),
(v_course_id, 'A sum term is:', 'multiple_choice', 'Variables ANDed together', 'Variables ORed together', 'Variables XORed together', 'Single variable only', 'B', 'Sum term uses OR operation between variables.'),
(v_course_id, 'A product term is:', 'multiple_choice', 'Variables ORed together', 'Variables ANDed together', 'Variables XORed together', 'Single variable only', 'B', 'Product term uses AND operation between variables.'),
(v_course_id, 'Standard form has at least one term that is:', 'multiple_choice', 'A minterm', 'A maxterm', 'NOT a minterm or maxterm', 'A literal', 'C', 'Standard form is less restrictive than canonical form.'),
(v_course_id, 'Non-standard form allows:', 'multiple_choice', 'Factoring out common variables', 'Only minterms', 'Only maxterms', 'No factoring', 'A', 'Non-standard form may have factored expressions.'),
(v_course_id, 'Switching algebra is also known as:', 'multiple_choice', 'Linear algebra', 'Boolean algebra', 'Abstract algebra', 'Vector algebra', 'B', 'Switching algebra is another name for Boolean algebra.'),
(v_course_id, 'Digital circuit diagrams are also called:', 'multiple_choice', 'Layouts', 'Schematic diagrams or schematics', 'Blueprints', 'Wiring diagrams', 'B', 'Schematics show logical connections.'),
(v_course_id, 'Synthesis of combinational circuits is the reverse of:', 'multiple_choice', 'Simulation', 'Analysis', 'Testing', 'Fabrication', 'B', 'Synthesis creates circuit from function; analysis derives function from circuit.'),
(v_course_id, 'The map method was first proposed by:', 'multiple_choice', 'Karnaugh', 'Veitch', 'Shannon', 'Boole', 'B', 'Veitch first proposed the diagram; Karnaugh popularized it.'),
(v_course_id, 'The Veitch diagram is also known as:', 'multiple_choice', 'Venn diagram', 'Karnaugh map', 'Truth table', 'Logic diagram', 'B', 'Veitch diagram and Karnaugh map are similar representations.'),
(v_course_id, 'A 0-subcube is:', 'multiple_choice', 'Four adjacent 1-minterms', 'Two adjacent 1-minterms', 'A single 1-minterm', 'All zeros', 'C', '0-subcube = single minterm (size 1).'),
(v_course_id, 'A 1-subcube is:', 'multiple_choice', 'A single 1-minterm', 'Two adjacent 1-minterms', 'Four adjacent 1-minterms', 'Eight adjacent 1-minterms', 'B', '1-subcube = pair of adjacent minterms (size 2).'),
(v_course_id, 'A 2-subcube has how many adjacent 1-minterms?', 'multiple_choice', '1', '2', '4', '8', 'C', '2-subcube = four adjacent minterms (size 4).'),
(v_course_id, 'The K-map goal is to:', 'multiple_choice', 'Maximize subcubes', 'Minimize number of subcubes covering all 1-minterms', 'Use only 0-subcubes', 'Avoid subcubes', 'B', 'Fewest subcubes = minimal expression.'),
(v_course_id, 'Latches and flip-flops are basic memory elements for:', 'multiple_choice', 'Storing programs', 'Storing information', 'Processing data', 'Amplifying signals', 'B', 'They store binary state information.'),
(v_course_id, 'The stored bit in a latch is referred to as the:', 'multiple_choice', 'Value', 'State', 'Output', 'Input', 'B', 'Current stored value is the state.'),
(v_course_id, 'A SET-CLEAR latch can also be called:', 'multiple_choice', 'SET-RESET latch', 'RESET latch', 'D latch', 'T latch', 'A', 'Set-Clear = Set-Reset (SR).'),
(v_course_id, 'Clearing a flip-flop means:', 'multiple_choice', 'Setting output to 1', 'Resetting output to 0', 'Toggling output', 'Disabling output', 'B', 'Clear = reset = set to 0.'),
(v_course_id, 'The normal output of a flip-flop is called:', 'multiple_choice', 'Q′', 'Q', 'CLK', 'RST', 'B', 'Q is the normal output; Q′ is complement.'),
(v_course_id, 'An S-R flip-flop has inputs named:', 'multiple_choice', 'Set and Toggle', 'Set and Reset', 'Set and Clear', 'Reset and Toggle', 'B', 'S-R = Set-Reset.'),
(v_course_id, 'A flip-flop is also known as:', 'multiple_choice', 'Monostable multivibrator', 'Astable multivibrator', 'Bistable multivibrator', 'Tristate buffer', 'C', 'Flip-flops have two stable states = bistable.'),
(v_course_id, 'Flip-flops can be constructed using:', 'multiple_choice', 'AND gates only', 'OR gates only', 'NAND or NOR gates', 'XOR gates only', 'C', 'Cross-coupled NAND or NOR gates form flip-flops.'),
(v_course_id, 'Synchronous circuits change state:', 'multiple_choice', 'Anytime inputs change', 'Only when clock pulses are present', 'Only on power-up', 'Randomly', 'B', 'Synchronous operation relies on clock edges.'),
(v_course_id, 'A flip-flop is edge-triggered while a latch is:', 'multiple_choice', 'Edge-triggered also', 'Level-sensitive', 'Pulse-triggered', 'Astable', 'B', 'Latches follow input while enabled; flip-flops sample on edges.'),
(v_course_id, 'What is false output count generation in asynchronous counters called?', 'multiple_choice', 'Glitch', 'Ripple effect', 'Race condition', 'Setup violation', 'B', 'Ripple effect causes temporary false outputs.'),
(v_course_id, 'A modulo-n counter has how many states?', 'multiple_choice', 'n', 'n+1', 'n-1', '2n', 'A', 'Modulo-n means n distinct states.'),
(v_course_id, 'A parallel down-counter uses inverted outputs to:', 'multiple_choice', 'Count up', 'Count down', 'Reset', 'Pause', 'B', 'Inverted outputs enable counting downward.'),
(v_course_id, 'Which adder adds two operands plus carry-in?', 'multiple_choice', 'Half adder', 'Full adder', 'Ripple adder', 'Carry adder', 'B', 'Full adder has three inputs: A, B, and Carry-in.'),
(v_course_id, 'The octal number 651.124 base8 is equivalent to:', 'multiple_choice', '1A9.2A base16', '1A8.2B base16', '2A9.1A base16', '1B9.2A base16', 'A', 'Conversion: octal 651 = 6×64+5×8+1= 384+40+1=425 decimal = 1A9 hex.');


INSERT INTO questions (course_id, question_text, question_type, correct_answer, explanation) VALUES
(v_course_id, 'Our world is an ________ world.', 'fill_in_blank', 'analog', 'Measurements of physical objects are continuous, not discrete.'),
(v_course_id, 'A single 0 or a single 1 is a binary digit or ________.', 'fill_in_blank', 'bit', 'A bit represents the smallest unit of binary data.'),
(v_course_id, 'BCD is the acronym for ________.', 'fill_in_blank', 'Binary Coded Decimal', 'BCD encodes each decimal digit with its binary equivalent.'),
(v_course_id, 'In a Boolean function, the ________ operator is denoted with a dot (.) or no symbol at all.', 'fill_in_blank', 'AND', 'AND operation is represented by multiplication or concatenation.'),
(v_course_id, 'The NOT operator is also known as the ________.', 'fill_in_blank', 'INVERTER', 'NOT gate inverts the input signal.'),
(v_course_id, '________ developed a system of mathematical logic called Boolean algebra in 1854.', 'fill_in_blank', 'George Boole', 'George Boole is the founder of Boolean algebra.'),
(v_course_id, 'In ________, Claude Shannon showed that circuits built with binary switches can be described using Boolean algebra.', 'fill_in_blank', '1938', 'Claude Shannon''s 1938 thesis connected Boolean algebra to switching circuits.'),
(v_course_id, 'The ________ states that if a Boolean expression is true, then its dual is also true.', 'fill_in_blank', 'duality principle', 'The duality principle is fundamental in Boolean algebra.'),
(v_course_id, 'A ________ is a product term that contains all the variables used in a function.', 'fill_in_blank', 'Minterm', 'A minterm includes every variable exactly once.'),
(v_course_id, 'A ________ is a sum term that contains all the variables used in the function.', 'fill_in_blank', 'Maxterm', 'A maxterm includes every variable exactly once in complemented or uncomplemented form.'),
(v_course_id, 'The NOT gate is also called the ________.', 'fill_in_blank', 'INVERTER', 'The NOT gate inverts the input signal.'),
(v_course_id, '________ circuits are the class of digital circuits where the outputs depend only on current inputs.', 'fill_in_blank', 'Combinational', 'Combinational circuits have no memory elements.'),
(v_course_id, '________ are circuits whose outputs depend on current inputs and all past inputs.', 'fill_in_blank', 'Sequential circuits', 'Sequential circuits have memory and feedback.'),
(v_course_id, 'The simplest memory circuit is called a ________.', 'fill_in_blank', 'bistable element', 'Two inverters connected in series form a bistable element.'),
(v_course_id, 'When two 1''s are fed back to the inputs producing 0 at outputs, this behavior is called the ________.', 'fill_in_blank', 'critical race', 'Critical race is an undesirable oscillating condition.'),
(v_course_id, 'The D latch with enable circuit is often referred to as a ________ latch.', 'fill_in_blank', 'transparent', 'Output follows input when enabled (transparent mode).'),
(v_course_id, 'There are basically ________ main types of flip-flops.', 'fill_in_blank', 'four', 'The four types are D, S-R, J-K, and T flip-flops.'),
(v_course_id, 'The most important memory element is the ________.', 'fill_in_blank', 'flip-flop', 'Flip-flops are edge-triggered memory elements.'),
(v_course_id, 'The universal measuring instrument used extensively in computer laboratory is the ________.', 'fill_in_blank', 'Cathode Ray Oscilloscope', 'CRO is used to observe electronic signals.'),
(v_course_id, 'The Quine-McCluskey or ________ method for reducing an equation is ideal for computer programming.', 'fill_in_blank', 'tabulation', 'Tabulation method is algorithmic and computer-friendly.'),
(v_course_id, 'A ________ is a prime implicant that includes a 1-minterm not included in any other prime implicant.', 'fill_in_blank', 'essential prime implicant', 'Essential prime implicants must be included in the minimal expression.'),
(v_course_id, 'To convert a binary number to octal, group bits into groups of ________.', 'fill_in_blank', 'threes', 'Three bits correspond to one octal digit.'),
(v_course_id, 'Hexadecimal numbers use base-________.', 'fill_in_blank', '16', 'Hexadecimal uses 16 digits (0-9, A-F).'),
(v_course_id, 'Octal numbers only use digits from 0 to ________.', 'fill_in_blank', '7', 'Octal is base-8, digits 0 through 7.'),
(v_course_id, 'The binary switch has ________ connections: input, output, and control.', 'fill_in_blank', 'three', 'A binary switch has three terminals.'),
(v_course_id, 'The action of clearing a Flip-Flop is also called ________.', 'fill_in_blank', 'resetting', 'Clearing sets the output to 0 (reset state).'),
(v_course_id, 'The T in T flip-flop stands for ________.', 'fill_in_blank', 'Toggle', 'T flip-flop toggles its output when T=1 and clock edge occurs.'),
(v_course_id, 'A CLEAR input can also be called ________ input.', 'fill_in_blank', 'RESET', 'Clear and reset are synonymous.'),
(v_course_id, 'In a ________ counter, each flip-flop is triggered by the previous flip-flop, causing a ripple effect.', 'fill_in_blank', 'asynchronous', 'Asynchronous counters have propagation delays that accumulate.'),
(v_course_id, 'A ________ changes state only at the active edge of its enable signal.', 'fill_in_blank', 'flip-flop', 'Flip-flops are edge-triggered, unlike level-sensitive latches.');

-- ============================================
-- MULTIPLE CHOICE QUESTIONS (170 questions)
-- ============================================

INSERT INTO questions (course_id, question_text, question_type, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(v_course_id, 'A string of n bits can represent how many different pieces of information?', 'multiple_choice', 'n', '2n', '2^n', 'n^2', 'C', 'A string of n bits can represent 2^n different combinations.'),
(v_course_id, 'The decimal digit 4 has a greater value than digit 8 because:', 'multiple_choice', '4 is larger than 8', '4 is in the tenth position while 8 is in the unit position', '8 is even', '4 comes before 8', 'B', 'Positional value matters; 4 in tens place equals 40, exceeding 8 in units place.'),
(v_course_id, 'Which of the following is NOT a basic logic gate?', 'multiple_choice', 'AND', 'OR', 'NOT', 'NAND', 'D', 'NAND is derived from AND and NOT; the three basic gates are AND, OR, NOT.'),
(v_course_id, 'What is the decimal equivalent of binary 1010?', 'multiple_choice', '8', '9', '10', '11', 'C', '1×8 + 0×4 + 1×2 + 0×1 = 8+2 = 10.'),
(v_course_id, 'Which gate outputs HIGH only when all inputs are HIGH?', 'multiple_choice', 'OR', 'AND', 'NOR', 'XOR', 'B', 'AND gate requires all inputs HIGH for output HIGH.'),
(v_course_id, 'Which gate outputs HIGH when at least one input is HIGH?', 'multiple_choice', 'AND', 'NOR', 'OR', 'NAND', 'C', 'OR gate outputs HIGH if any input is HIGH.'),
(v_course_id, 'DeMorgan''s theorem states that (x·y)′ = ?', 'multiple_choice', 'x′ + y′', 'x′·y′', 'x + y', 'x·y', 'A', 'DeMorgan''s first law: complement of AND equals OR of complements.'),
(v_course_id, 'DeMorgan''s theorem states that (x+y)′ = ?', 'multiple_choice', 'x′ + y′', 'x′·y′', 'x + y', 'x·y', 'B', 'DeMorgan''s second law: complement of OR equals AND of complements.'),
(v_course_id, 'What is the octal equivalent of binary 111 010?', 'multiple_choice', '62', '72', '70', '65', 'B', '111=7, 010=2 → 72 in octal.'),
(v_course_id, 'The hexadecimal digit A represents what decimal value?', 'multiple_choice', '9', '10', '11', '12', 'B', 'A = 10 in decimal.'),
(v_course_id, 'Which flip-flop eliminates the indeterminate condition of the S-R flip-flop?', 'multiple_choice', 'T flip-flop', 'D flip-flop', 'J-K flip-flop', 'R-S flip-flop', 'C', 'J-K flip-flop has toggling mode when J=K=1, no indeterminate state.'),
(v_course_id, 'In a K-map, a pair of adjacent 1s represents elimination of how many variables?', 'multiple_choice', '0', '1', '2', '3', 'B', 'A 1-subcube (two adjacent minterms) eliminates one variable.'),
(v_course_id, 'A 4-variable K-map has how many cells?', 'multiple_choice', '4', '8', '16', '32', 'C', '4-variable K-map has 2^4 = 16 cells.'),
(v_course_id, 'What is the main advantage of synchronous counters over asynchronous counters?', 'multiple_choice', 'Lower cost', 'Higher speed', 'Simplicity', 'Uses fewer flip-flops', 'B', 'Synchronous counters operate faster because no accumulated propagation delay.'),
(v_course_id, 'Which gate is known as a coincidence detector?', 'multiple_choice', 'OR gate', 'AND gate', 'NAND gate', 'XOR gate', 'B', 'AND gate outputs HIGH only when all inputs coincide as HIGH.'),
(v_course_id, 'The output of an EX-NOR gate is 1 when:', 'multiple_choice', 'inputs are different', 'inputs are same', 'at least one input is 1', 'both inputs are 0 only', 'B', 'EX-NOR outputs 1 when both inputs are equal (both 0 or both 1).'),
(v_course_id, 'Which of the following is a universal gate?', 'multiple_choice', 'AND', 'OR', 'NOT', 'NAND', 'D', 'NAND gate can be used to create AND, OR, and NOT functions.'),
(v_course_id, 'A half adder adds:', 'multiple_choice', 'two bits and carry-in', 'two bits only', 'three bits', 'one bit only', 'B', 'Half adder adds two single bits, producing sum and carry-out.'),
(v_course_id, 'A full adder adds:', 'multiple_choice', 'two bits only', 'three bits (two operands plus carry-in)', 'four bits', 'one bit only', 'B', 'Full adder adds two bits and a carry-in from previous stage.'),
(v_course_id, 'What does PLD stand for?', 'multiple_choice', 'Programmable Logic Device', 'Power Logic Device', 'Primary Logic Diagram', 'Parallel Logic Driver', 'A', 'PLDs are ICs that can be programmed to execute complex logic functions.'),
(v_course_id, 'Which of the following is NOT a type of counter mentioned?', 'multiple_choice', 'Ring counter', 'Gray-code counter', 'Binary counter', 'Decimal counter', 'D', 'Binary, ring, and gray-code counters are mentioned; decimal is not listed as a separate type.'),
(v_course_id, 'The MOD number of a counter equals:', 'multiple_choice', 'number of flip-flops', 'number of states before recycling', 'clock frequency', 'output voltage', 'B', 'MOD is the number of distinct states in one complete cycle.'),
(v_course_id, 'What is the simplest counter to build?', 'multiple_choice', 'Synchronous counter', 'Ring counter', 'Ripple counter', 'Gray-code counter', 'C', 'Ripple/asynchronous counters are simplest due to cascaded structure.'),
(v_course_id, 'Which flip-flop is NOT level-sensitive?', 'multiple_choice', 'Latch', 'D latch', 'SR latch', 'Flip-flop', 'D', 'Flip-flops are edge-triggered, latches are level-sensitive.'),
(v_course_id, 'What is the characteristic equation of an SR latch?', 'multiple_choice', 'Q(n+1)=S+RQ(n)', 'Q(n+1)=S+R''Q(n)', 'Q(n+1)=S''+RQ(n)', 'Q(n+1)=S+Q(n)', 'B', 'The characteristic equation is Q(n+1) = (S + Q(n))R''.'),
(v_course_id, 'Which logic family has military grade with wider supply voltage range?', 'multiple_choice', '7400 series', '5400 series', '4000 series', '74LS series', 'B', '5400 series are military grade, 7400 series are commercial.'),
(v_course_id, 'How many full adders are needed for an m-bit parallel adder?', 'multiple_choice', 'm', 'm-1', 'm+1', '2m', 'A', 'An m-bit parallel adder requires m full adders (or one half adder and m-1 full adders).'),
(v_course_id, 'Which gate output is 1 if inputs are different?', 'multiple_choice', 'AND', 'OR', 'XOR', 'XNOR', 'C', 'XOR (exclusive OR) outputs 1 when inputs differ.'),
(v_course_id, 'What does IEEE stand for?', 'multiple_choice', 'Institute of Electrical and Electronics Engineers', 'International Electrical and Electronic Engineers', 'Institute of Energy and Electronic Engineering', 'International Energy and Electrical Engineers', 'A', 'IEEE is the Institute of Electrical and Electronics Engineers.'),
(v_course_id, 'What is the hexadecimal equivalent of decimal 170?', 'multiple_choice', 'A0', 'AA', 'AB', 'A1', 'B', '170 ÷ 16 = 10 remainder 10 → AA (A=10).'),
(v_course_id, 'Convert hex 1E2 to decimal:', 'multiple_choice', '480', '482', '484', '486', 'B', '1×256 + 14×16 + 2 = 256 + 224 + 2 = 482.'),
(v_course_id, 'The octal equivalent of decimal 417 is:', 'multiple_choice', '641', '640', '642', '631', 'A', '417 ÷ 8 = 52 r1, 52 ÷ 8 = 6 r4, 6 ÷ 8 = 0 r6 → 641 octal.'),
(v_course_id, 'How many minterms exist for 3 variables?', 'multiple_choice', '4', '6', '8', '16', 'C', '2^3 = 8 minterms for 3 variables.'),
(v_course_id, 'A 3-variable K-map has how many cells?', 'multiple_choice', '4', '8', '16', '9', 'B', '3-variable K-map has 2^3 = 8 cells.'),
(v_course_id, 'Which gate can be constructed by AND, OR, and NOT gates?', 'multiple_choice', 'NAND only', 'NOR only', 'All gates', 'XOR only', 'C', 'AND, OR, NOT are universal; any gate can be constructed from them.'),
(v_course_id, 'What is the main disadvantage of asynchronous counters?', 'multiple_choice', 'High power consumption', 'Propagation delay accumulation', 'Complex design', 'Limited count range', 'B', 'Ripple effect causes false outputs due to accumulated delays.'),
(v_course_id, 'A bistable element has how many stable states?', 'multiple_choice', 'One', 'Two', 'Three', 'Four', 'B', 'Bistable means two stable states (0 and 1).'),
(v_course_id, 'What is the major advantage of synchronous counters over asynchronous?', 'multiple_choice', 'Higher speed operation', 'Lower cost', 'Fewer gates', 'Easier to design', 'A', 'Synchronous counters operate faster with no ripple delay accumulation.'),
(v_course_id, 'The NAND gate is derived from AND gate and:', 'multiple_choice', 'OR gate', 'NOT gate in series', 'XOR gate', 'Buffer', 'B', 'NAND = AND followed by NOT (inverter).'),
(v_course_id, 'Which flip-flop type has a toggling operation when both inputs are 1?', 'multiple_choice', 'D flip-flop', 'T flip-flop', 'J-K flip-flop', 'SR flip-flop', 'C', 'J-K flip-flop toggles when J=K=1.'),
(v_course_id, 'What does GAL stand for?', 'multiple_choice', 'General Array Logic', 'Generic Array Logic', 'Gate Array Logic', 'Global Array Logic', 'B', 'GAL is Generic Array Logic, a type of programmable logic device.'),
(v_course_id, 'The AND operation can be described as Boolean:', 'multiple_choice', 'Addition', 'Multiplication', 'Subtraction', 'Division', 'B', 'AND corresponds to multiplication in Boolean algebra.'),
(v_course_id, 'The OR operation can be described as Boolean:', 'multiple_choice', 'Addition', 'Multiplication', 'Subtraction', 'Division', 'A', 'OR corresponds to addition in Boolean algebra.'),
(v_course_id, 'Which logic gate is most universally used?', 'multiple_choice', 'AND', 'OR', 'NOT', 'NAND', 'D', 'NAND is universal and widely used in IC design.'),
(v_course_id, 'A single latch can store how many bits?', 'multiple_choice', 'One', 'Two', 'Four', 'Eight', 'A', 'A single latch stores exactly 1 bit of information.'),
(v_course_id, 'Which of the following is level-sensitive?', 'multiple_choice', 'Flip-flop', 'Latch', 'Register', 'Counter', 'B', 'Latches are level-sensitive; flip-flops are edge-triggered.'),
(v_course_id, 'What is the binary equivalent of decimal 15?', 'multiple_choice', '1110', '1111', '1101', '1010', 'B', '8+4+2+1 = 15, binary 1111.'),
(v_course_id, 'What is the binary equivalent of octal 17?', 'multiple_choice', '1111', '1110', '1010', '1101', 'A', 'Octal 1 = 001, 7 = 111 → binary 001111 = 1111.'),
(v_course_id, 'What is the primary difference between 5400 and 7400 series ICs?', 'multiple_choice', 'Pin count differs', '5400 series is military grade with wider voltage/temperature range', '7400 series is faster', '5400 series uses more power', 'B', '5400 series military grade, 7400 commercial grade.'),
(v_course_id, 'What is the expression for AND gate output?', 'multiple_choice', 'A+B', 'A·B', 'A⊕B', 'A′+B′', 'B', 'AND output is A multiplied by B (A·B).'),
(v_course_id, 'Which of the following cannot be a Boolean variable value?', 'multiple_choice', '0', '1', '2', 'Both 0 and 1', 'C', 'Boolean variables are binary, only 0 or 1.'),
(v_course_id, 'A product term containing all variables is a:', 'multiple_choice', 'Maxterm', 'Minterm', 'Sum term', 'Literal', 'B', 'Minterm is a product term with all variables.'),
(v_course_id, 'A sum term containing all variables is a:', 'multiple_choice', 'Minterm', 'Maxterm', 'Product term', 'Literal', 'B', 'Maxterm is a sum term with all variables.'),
(v_course_id, 'Canonical form expresses a function as:', 'multiple_choice', 'sum of minterms or product of maxterms', 'product of minterms', 'sum of maxterms', 'any random form', 'A', 'Canonical form is either sum of minterms or product of maxterms.'),
(v_course_id, 'What is the dual of expression x·y′ + z?', 'multiple_choice', 'x′+y·z′', 'x+y′·z', '(x+y′)·z', 'x·(y′+z)', 'B', 'Duality swaps + with · and 0 with 1.'),
(v_course_id, 'Which theorem states (x·y)′ = x′+y′?', 'multiple_choice', 'DeMorgan''s theorem', 'Duality principle', 'Absorption theorem', 'Idempotent theorem', 'A', 'DeMorgan''s theorem defines complement of AND/OR operations.'),
(v_course_id, 'A Karnaugh map is a graphical representation of:', 'multiple_choice', 'Boolean function', 'Circuit diagram', 'Truth table', 'Both A and C', 'D', 'K-map represents truth table graphically and helps simplify Boolean functions.'),
(v_course_id, 'To interface TTL to CMOS, what is required?', 'multiple_choice', 'Pull-down resistor', 'Pull-up resistor to Vcc', 'Direct connection', 'Buffer gate only', 'B', 'A pull-up resistor between TTL output and Vcc is needed.'),
(v_course_id, 'Low-power Schottky TTL uses less power because:', 'multiple_choice', 'Lower voltage', 'Larger value resistor', 'Fewer transistors', 'Smaller die size', 'B', 'Larger resistor values limit current, reducing power consumption.'),
(v_course_id, 'An OR gate can be imagined as:', 'multiple_choice', 'Switches in series', 'Switches in parallel', 'Switches in series-parallel', 'A single switch', 'B', 'Parallel switches correspond to OR logic.'),
(v_course_id, 'What is propagation time?', 'multiple_choice', 'Time for signal to travel', 'Time for gate to change state', 'Clock period', 'Setup time', 'B', 'Propagation delay is time for output to change after input changes.'),
(v_course_id, 'Which statement about the SR latch is correct?', 'multiple_choice', 'Works when both inputs are 0', 'Works when both inputs are 1', 'Has indeterminate condition when both inputs 1', 'Never has indeterminate condition', 'C', 'SR latch has invalid/indeterminate state when S=1,R=1.'),
(v_course_id, 'The output of SR latch consists of:', 'multiple_choice', 'Q only', 'Q and Q′ (complement)', 'Q and clock', 'Only complement', 'B', 'SR latch has normal output Q and complementary output Q''.'),
(v_course_id, 'How many inputs does an SR latch have?', 'multiple_choice', '1', '2', '3', '4', 'B', 'SR latch has Set and Reset inputs (2 inputs).'),
(v_course_id, 'Which of the following is NOT a type of flip-flop?', 'multiple_choice', 'D flip-flop', 'S-R flip-flop', 'J-K flip-flop', 'X-Y flip-flop', 'D', 'D, S-R, J-K, and T are the four main types.'),
(v_course_id, 'What does the clock signal typically look like?', 'multiple_choice', 'Sine wave', 'Triangular wave', 'Rectangular pulse train', 'Spike', 'C', 'Clock signals are rectangular/square waves.'),
(v_course_id, 'Positive-going transition (PGT) occurs when clock goes:', 'multiple_choice', '1 to 0', '0 to 1', 'X to Z', 'Z to X', 'B', 'PGT is rising edge (0 to 1 transition).'),
(v_course_id, 'Negative-going transition (NGT) occurs when clock goes:', 'multiple_choice', '1 to 0', '0 to 1', 'X to Z', 'Z to X', 'A', 'NGT is falling edge (1 to 0 transition).'),
(v_course_id, 'Most digital systems are principally:', 'multiple_choice', 'Asynchronous', 'Synchronous', 'Combinational', 'Analog', 'B', 'Most digital systems use synchronous design with a clock.'),
(v_course_id, 'A master-slave flip-flop consists of:', 'multiple_choice', 'One flip-flop', 'Two flip-flops (master and slave)', 'Three flip-flops', 'Four latches', 'B', 'Master-slave uses master and slave stages.'),
(v_course_id, 'What is a ripple counter?', 'multiple_choice', 'Each flip-flop clocked by previous output', 'All flip-flops clocked together', 'Counter with no propagation delay', 'Counter with gray code output', 'A', 'Ripple/asynchronous counters have cascaded clocking causing ripple effect.'),
(v_course_id, 'A BCD counter counts from:', 'multiple_choice', '0 to 15', '0 to 9 then recycles', '0 to 7', '1 to 10', 'B', 'BCD counter counts 0 through 9 (decimal digits).'),
(v_course_id, 'Down counters are:', 'multiple_choice', 'More common than up counters', 'Less common than up counters', 'Equally common', 'Never used', 'B', 'Down counters are not as widely used as up counters.'),
(v_course_id, 'A synchronous counter''s propagation delay is approximately:', 'multiple_choice', 'One flip-flop delay plus gate delay', 'Sum of all flip-flop delays', 'Clock period', 'Zero', 'A', 'Delay is one flip-flop toggle time plus AND gate delay.'),
(v_course_id, 'An n-bit binary counter has states from 0 to:', 'multiple_choice', 'n', '2n', '2^n - 1', '2^n', 'C', 'n-bit binary counter counts 0 to 2^n - 1 (total 2^n states).'),
(v_course_id, 'To count 1000 items, how many flip-flops are needed?', 'multiple_choice', '8', '9', '10', '11', 'C', '2^9 = 512, 2^10 = 1024 → need 10 flip-flops.'),
(v_course_id, 'An n-bit binary counter repeats every:', 'multiple_choice', 'n clock pulses', '2n clock pulses', '2^n clock pulses', 'n^2 clock pulses', 'C', 'Complete cycle requires 2^n clock pulses.'),
(v_course_id, 'Which flip-flop is best for counter design where toggling is required?', 'multiple_choice', 'D flip-flop', 'T flip-flop', 'SR flip-flop', 'JK flip-flop with tied inputs', 'D', 'JK with J=K=1 toggles, also T flip-flop is purpose-built for toggling.'),
(v_course_id, 'For battery-operated digital watches, the basic frequency comes from:', 'multiple_choice', 'AC power line', 'Quartz-crystal oscillator', 'RC circuit', 'LC tank', 'B', 'Quartz crystals provide stable, accurate frequency.'),
(v_course_id, 'Digital clocks operated from AC power line use what frequency?', 'multiple_choice', '60 Hz only', '50 Hz only', 'Either 50 or 60 Hz depending on region', '100 Hz', 'C', 'AC line frequency is 50 Hz (Europe/Asia) or 60 Hz (Americas).'),
(v_course_id, 'In a parallel counter, flip-flops change state:', 'multiple_choice', 'Sequentially', 'Simultaneously', 'Randomly', 'Only on negative edge', 'B', 'Parallel/synchronous counters have simultaneous state changes.'),
(v_course_id, 'Which statement about asynchronous counters is FALSE?', 'multiple_choice', 'Propagation delays add up', 'False outputs may occur', 'Fastest counter type', 'Simple to build', 'C', 'Asynchronous counters are slowest due to accumulated delays.'),
(v_course_id, 'A ring counter starts with:', 'multiple_choice', 'All zeros', 'All ones', 'String of 0 bits followed by one 1-bit', 'Alternating bits', 'C', 'Ring counter typically has a single 1 shifting through zeros.'),
(v_course_id, 'Gray-code counter has consecutive values differing in:', 'multiple_choice', 'All bits', 'One bit only', 'Two bits', 'No bits', 'B', 'Gray code ensures adjacent values differ in exactly one bit.'),
(v_course_id, 'What is a prime implicant?', 'multiple_choice', 'Any product term', 'Subcube not contained in any larger subcube', 'Essential term', 'Don''t care term', 'B', 'Prime implicant is a maximal subcube not contained in another subcube.'),
(v_course_id, 'What is the result of x·x + y?', 'multiple_choice', 'x', 'y', 'x+y', '1', 'C', 'x·x = x, so x + y.'),
(v_course_id, 'Which of the following is FALSE about octal numbers?', 'multiple_choice', 'Use digits 0-7', 'Base-8 system', 'Use digits 0-8', 'Group binary in threes', 'C', 'Octal uses digits 0-7 only, not 8.'),
(v_course_id, 'Two switches in series give rise to which logical operator?', 'multiple_choice', 'OR', 'AND', 'NOT', 'XOR', 'B', 'Series connection implements AND logic.'),
(v_course_id, 'Two switches in parallel give rise to which logical operator?', 'multiple_choice', 'AND', 'OR', 'NOT', 'NAND', 'B', 'Parallel connection implements OR logic.'),
(v_course_id, 'A binary switch has how many connections?', 'multiple_choice', 'One', 'Two', 'Three', 'Four', 'C', 'Binary switch has input, output, and control (3 connections).'),
(v_course_id, 'A truth table is a(n):', 'multiple_choice', 'One-dimensional array', 'Two-dimensional array', 'Graph', 'Equation', 'B', 'Truth tables have rows and columns (inputs and outputs).'),
(v_course_id, 'Boolean algebra is a tool for:', 'multiple_choice', 'Digital system analysis and design', 'Analog circuit design', 'Power systems', 'Mechanical engineering', 'A', 'Boolean algebra is fundamental to digital logic design.'),
(v_course_id, 'Boolean theorems help to:', 'multiple_choice', 'Complicate logic', 'Simplify logic expressions and circuits', 'Convert to analog', 'Increase power consumption', 'B', 'Theorems minimize logic for simpler, cheaper circuits.'),
(v_course_id, 'What is the inverse of function F denoted by?', 'multiple_choice', 'F+', 'F-', 'F′ or ¬F', 'F*', 'C', 'Prime notation or overbar denotes complement/inverse.'),
(v_course_id, 'A sum term is:', 'multiple_choice', 'Variables ANDed together', 'Variables ORed together', 'Variables XORed together', 'Single variable only', 'B', 'Sum term uses OR operation between variables.'),
(v_course_id, 'A product term is:', 'multiple_choice', 'Variables ORed together', 'Variables ANDed together', 'Variables XORed together', 'Single variable only', 'B', 'Product term uses AND operation between variables.'),
(v_course_id, 'Standard form has at least one term that is:', 'multiple_choice', 'A minterm', 'A maxterm', 'NOT a minterm or maxterm', 'A literal', 'C', 'Standard form is less restrictive than canonical form.'),
(v_course_id, 'Non-standard form allows:', 'multiple_choice', 'Factoring out common variables', 'Only minterms', 'Only maxterms', 'No factoring', 'A', 'Non-standard form may have factored expressions.'),
(v_course_id, 'Switching algebra is also known as:', 'multiple_choice', 'Linear algebra', 'Boolean algebra', 'Abstract algebra', 'Vector algebra', 'B', 'Switching algebra is another name for Boolean algebra.'),
(v_course_id, 'Digital circuit diagrams are also called:', 'multiple_choice', 'Layouts', 'Schematic diagrams or schematics', 'Blueprints', 'Wiring diagrams', 'B', 'Schematics show logical connections.'),
(v_course_id, 'Synthesis of combinational circuits is the reverse of:', 'multiple_choice', 'Simulation', 'Analysis', 'Testing', 'Fabrication', 'B', 'Synthesis creates circuit from function; analysis derives function from circuit.'),
(v_course_id, 'The map method was first proposed by:', 'multiple_choice', 'Karnaugh', 'Veitch', 'Shannon', 'Boole', 'B', 'Veitch first proposed the diagram; Karnaugh popularized it.'),
(v_course_id, 'The Veitch diagram is also known as:', 'multiple_choice', 'Venn diagram', 'Karnaugh map', 'Truth table', 'Logic diagram', 'B', 'Veitch diagram and Karnaugh map are similar representations.'),
(v_course_id, 'A 0-subcube is:', 'multiple_choice', 'Four adjacent 1-minterms', 'Two adjacent 1-minterms', 'A single 1-minterm', 'All zeros', 'C', '0-subcube = single minterm (size 1).'),
(v_course_id, 'A 1-subcube is:', 'multiple_choice', 'A single 1-minterm', 'Two adjacent 1-minterms', 'Four adjacent 1-minterms', 'Eight adjacent 1-minterms', 'B', '1-subcube = pair of adjacent minterms (size 2).'),
(v_course_id, 'A 2-subcube has how many adjacent 1-minterms?', 'multiple_choice', '1', '2', '4', '8', 'C', '2-subcube = four adjacent minterms (size 4).'),
(v_course_id, 'The K-map goal is to:', 'multiple_choice', 'Maximize subcubes', 'Minimize number of subcubes covering all 1-minterms', 'Use only 0-subcubes', 'Avoid subcubes', 'B', 'Fewest subcubes = minimal expression.'),
(v_course_id, 'Latches and flip-flops are basic memory elements for:', 'multiple_choice', 'Storing programs', 'Storing information', 'Processing data', 'Amplifying signals', 'B', 'They store binary state information.'),
(v_course_id, 'The stored bit in a latch is referred to as the:', 'multiple_choice', 'Value', 'State', 'Output', 'Input', 'B', 'Current stored value is the state.'),
(v_course_id, 'A SET-CLEAR latch can also be called:', 'multiple_choice', 'SET-RESET latch', 'RESET latch', 'D latch', 'T latch', 'A', 'Set-Clear = Set-Reset (SR).'),
(v_course_id, 'Clearing a flip-flop means:', 'multiple_choice', 'Setting output to 1', 'Resetting output to 0', 'Toggling output', 'Disabling output', 'B', 'Clear = reset = set to 0.'),
(v_course_id, 'The normal output of a flip-flop is called:', 'multiple_choice', 'Q′', 'Q', 'CLK', 'RST', 'B', 'Q is the normal output; Q′ is complement.'),
(v_course_id, 'An S-R flip-flop has inputs named:', 'multiple_choice', 'Set and Toggle', 'Set and Reset', 'Set and Clear', 'Reset and Toggle', 'B', 'S-R = Set-Reset.'),
(v_course_id, 'A flip-flop is also known as:', 'multiple_choice', 'Monostable multivibrator', 'Astable multivibrator', 'Bistable multivibrator', 'Tristate buffer', 'C', 'Flip-flops have two stable states = bistable.'),
(v_course_id, 'Flip-flops can be constructed using:', 'multiple_choice', 'AND gates only', 'OR gates only', 'NAND or NOR gates', 'XOR gates only', 'C', 'Cross-coupled NAND or NOR gates form flip-flops.'),
(v_course_id, 'Synchronous circuits change state:', 'multiple_choice', 'Anytime inputs change', 'Only when clock pulses are present', 'Only on power-up', 'Randomly', 'B', 'Synchronous operation relies on clock edges.'),
(v_course_id, 'A flip-flop is edge-triggered while a latch is:', 'multiple_choice', 'Edge-triggered also', 'Level-sensitive', 'Pulse-triggered', 'Astable', 'B', 'Latches follow input while enabled; flip-flops sample on edges.'),
(v_course_id, 'What is false output count generation in asynchronous counters called?', 'multiple_choice', 'Glitch', 'Ripple effect', 'Race condition', 'Setup violation', 'B', 'Ripple effect causes temporary false outputs.'),
(v_course_id, 'A modulo-n counter has how many states?', 'multiple_choice', 'n', 'n+1', 'n-1', '2n', 'A', 'Modulo-n means n distinct states.'),
(v_course_id, 'A parallel down-counter uses inverted outputs to:', 'multiple_choice', 'Count up', 'Count down', 'Reset', 'Pause', 'B', 'Inverted outputs enable counting downward.'),
(v_course_id, 'Which adder adds two operands plus carry-in?', 'multiple_choice', 'Half adder', 'Full adder', 'Ripple adder', 'Carry adder', 'B', 'Full adder has three inputs: A, B, and Carry-in.'),
(v_course_id, 'The octal number 651.124 base8 is equivalent to:', 'multiple_choice', '1A9.2A base16', '1A8.2B base16', '2A9.1A base16', '1B9.2A base16', 'A', 'Octal 651 = 425 decimal = 1A9 hex; fractional part converts accordingly.'),
(v_course_id, 'The hexadecimal number 1E.53 base16 is equivalent to:', 'multiple_choice', '36.246 base8', '37.246 base8', '36.236 base8', '37.236 base8', 'A', '1E.53 hex = 30.324 decimal = 36.246 octal.'),
(v_course_id, 'Which of the following statements apply to CMOS devices?', 'multiple_choice', 'Low power consumption', 'High noise immunity', 'Wide supply voltage range', 'All of the options', 'D', 'CMOS devices have all these advantages.'),
(v_course_id, 'What causes low-power Schottky TTL to use less power?', 'multiple_choice', 'Lower voltage', 'A larger value resistor', 'Fewer transistors', 'Smaller die size', 'B', 'A larger resistor limits current, reducing power.'),
(v_course_id, 'What must be done to interface TTL to CMOS?', 'multiple_choice', 'Use a pull-down resistor', 'Use a pull-up resistor between TTL output and Vcc', 'Connect directly', 'Use a buffer', 'B', 'A pull-up resistor ensures proper high-level voltage.'),
(v_course_id, 'An OR gate can be imagined as:', 'multiple_choice', 'Switches in series', 'Switches in parallel', 'Switches in series-parallel', 'A single switch', 'B', 'Parallel switches give OR logic.'),
(v_course_id, 'Which gate is known as a coincidence detector?', 'multiple_choice', 'OR gate', 'AND gate', 'NOR gate', 'XOR gate', 'B', 'AND detects when all inputs coincide as HIGH.'),
(v_course_id, 'In case of XOR/XNOR simplification, we look for:', 'multiple_choice', 'Only diagonal adjacencies', 'Only offset adjacencies', 'Both diagonal and offset adjacencies', 'No adjacencies', 'C', 'XOR/XNOR simplifications use both diagonal and offset patterns.'),
(v_course_id, 'How many cells are in a 4-variable K-map?', 'multiple_choice', '4', '8', '16', '32', 'C', '2^4 = 16 cells.'),
(v_course_id, 'How many types of flip-flops do we have?', 'multiple_choice', '2', '3', '4', '5', 'C', 'D, S-R, J-K, and T are the four main types.'),
(v_course_id, 'The output of an EX-NOR gate is 1. Which input combination is correct?', 'multiple_choice', 'A=0, B=0', 'A=0, B=1', 'A=1, B=0', 'All of the above', 'A', 'EX-NOR outputs 1 when inputs are equal (both 0 or both 1).'),
(v_course_id, 'Which of the following gates output is 1 if and only if at least one input is 1?', 'multiple_choice', 'AND', 'OR', 'NAND', 'NOR', 'B', 'OR outputs 1 when any input is 1.'),
(v_course_id, 'The time required for a gate to change its state is called:', 'multiple_choice', 'Setup time', 'Hold time', 'Propagation time', 'Rise time', 'C', 'Propagation delay is the switching time.'),
(v_course_id, 'SOP expressions can be implemented using:', 'multiple_choice', 'AND-OR or NAND-NAND logic', 'OR-AND only', 'XOR only', 'NOT only', 'A', 'Sum-of-products maps to AND-OR or equivalent NAND-NAND.'),
(v_course_id, 'How many full adders are required for an m-bit parallel adder?', 'multiple_choice', 'm', 'm-1', 'm+1', '2m', 'A', 'm-bit adder needs m full adders (or one half adder + m-1 full adders).'),
(v_course_id, 'The main disadvantage of asynchronous counters over synchronous is their:', 'multiple_choice', 'Cost', 'Size', 'Propagation delay', 'Power consumption', 'C', 'Accumulated delays cause slower operation.'),
(v_course_id, 'The exclusive-OR gate can be constructed using AND, OR, and which gate?', 'multiple_choice', 'NAND', 'NOR', 'NOT', 'XNOR', 'C', 'XOR = A·B′ + A′·B requires AND, OR, and NOT.'),
(v_course_id, 'The decimal number system is a ________ system.', 'multiple_choice', 'Binary', 'Positional', 'Non-positional', 'Random', 'B', 'Decimal is positional (each digit''s value depends on position).'),
(v_course_id, 'A term with variable(s) ORed together is a:', 'multiple_choice', 'Product term', 'Sum term', 'Minterm', 'Maxterm', 'B', 'Sum term uses OR operations.'),
(v_course_id, 'A term with variable(s) ANDed together is a:', 'multiple_choice', 'Product term', 'Sum term', 'Minterm', 'Maxterm', 'A', 'Product term uses AND operations.'),
(v_course_id, 'The dual of logic expression (x·y′+z)·(x+1) is:', 'multiple_choice', '(x′+y·z′)+(x·0)', '(x′+y′·z)+(x·0)', '(x+y′+z)+(x·1)', '(x′+y·z)+(x·0)', 'A', 'Duality swaps + with ·, 0 with 1, and complements variables.'),
(v_course_id, 'Which of the following flip-flops cannot result in more complex design when used in building counter circuits?', 'multiple_choice', 'T', 'SR', 'JK', 'D', 'D', 'D flip-flops are simplest for counters.'),
(v_course_id, 'What is the binary representation of octal 44738?', 'multiple_choice', '100100111111', '100100111011', '100100111110', '100100111101', 'B', '4=100, 4=100, 7=111, 3=011 → 100100111011.'),
(v_course_id, 'The largest subcube is known as a:', 'multiple_choice', 'Minterm', 'Maxterm', 'Prime implicant', 'Essential prime implicant', 'C', 'Prime implicants are maximal subcubes.'),
(v_course_id, 'The difference between a flip-flop and a latch is:', 'multiple_choice', 'Latches have two inputs but flip-flops have two', 'Flip-flops are edge-triggered, latches are level-sensitive', 'Latches store more bits', 'No difference', 'B', 'Edge-triggered vs level-sensitive is the key distinction.'),
(v_course_id, 'The NAND latch works when both inputs are:', 'multiple_choice', '0', '1', 'Don''t care', 'Floating', 'B', 'NAND latch is active when both inputs are 1 (inactive state).'),
(v_course_id, 'Which of the following is NOT a type of counter?', 'multiple_choice', 'Ring', 'Binary', 'Gray-code', 'Binary Up', 'D', 'Binary Up is not a distinct counter type; it''s a binary counter that counts up.'),
(v_course_id, 'x·x + y = x is an example of which theorem?', 'multiple_choice', 'DeMorgan''s', 'Associative', 'Absorption', 'Idempotent', 'C', 'Absorption law: x + xy = x, or x(x+y) = x.'),
(v_course_id, 'Any Boolean function expressed as a sum of minterms is in its:', 'multiple_choice', 'Standard form', 'Canonical form', 'Reduced form', 'Non-standard form', 'B', 'Sum of minterms is canonical sum-of-products form.'),
(v_course_id, 'The simplest memory circuit is:', 'multiple_choice', 'SR latch', 'Bistable element', 'D latch', 'Flip-flop', 'B', 'Two cross-coupled inverters form the simplest bistable element.'),
(v_course_id, 'Which is NOT true about octal numbers?', 'multiple_choice', 'Use digits 0-7', 'Base-8 system', 'Use digits 0-8', 'Group binary in threes', 'C', 'Octal never uses digit 8.'),
(v_course_id, 'The SR latch is sensitive to its inputs:', 'multiple_choice', 'Only on clock edge', 'All the time', 'Only when enabled', 'Only on negative edge', 'B', 'Latches are level-sensitive (all the time when enabled).'),
(v_course_id, 'A Karnaugh map is a ________ representation of a truth table.', 'multiple_choice', 'Textual', 'Graphical', 'Tabular', 'Numerical', 'B', 'K-map is a graphical representation.'),
(v_course_id, 'The 4-bit input encodes the binary representation of a ________ digit.', 'multiple_choice', 'Binary', 'Octal', 'Decimal', 'Hexadecimal', 'C', '4-bit BCD encodes decimal digits.'),
(v_course_id, 'When the hours counter reaches 12, it is reset to zero by which gate?', 'multiple_choice', 'AND', 'OR', 'NAND', 'NOR', 'C', 'NAND gate detects 12 (binary 1100) to reset.'),
(v_course_id, 'One basic piece of test equipment for digital troubleshooting is the:', 'multiple_choice', 'Multimeter', 'Logic Probe', 'Oscilloscope', 'Function generator', 'B', 'Logic probe is specifically for digital signal troubleshooting.'),
(v_course_id, 'Whenever both data inputs J and K are at 1, the flip-flop is in a ________ state.', 'multiple_choice', 'Hold', 'Reset', 'Set', 'Toggle', 'D', 'J=K=1 causes toggling on each clock edge.');

END $$;