DO $$ DECLARE v_course_id UUID; BEGIN
SELECT id INTO v_course_id FROM courses WHERE code = 'GST204' LIMIT 1;
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to______, economic incentives are the main drive for the entrepreneurial activities.','multiple_choice','mobilize resources to meet it.','G.F. Papanek and J.R. Harris','addition to the general framework.','resources','B','Answer: G.F. Papanek and J.R. Harris');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The econ omic theory of entrepreneurship is sub -divided into ______','multiple_choice','depict the behaviour of certain group or people.','three','culture','activities.','B','Answer: three');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to_____, it is the high need for achievement which drives people towards','multiple_choice','1755','self-confidence','innovation strategy.','entrepreneurial activities.','D','Answer: entrepreneurial activities.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ can affect entrepreneurial activity positively because the only way to be independent is to','multiple_choice','cool','Stephenson (2010) believes that entre preneurial characteristics are','value','be an entrepreneur.','D','Answer: be an entrepreneur.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Schumpeter (1934) described ______ as a driver of market -based systems.','multiple_choice','risks.','entrepreneurship','uncertainty when exploiting opportunities','value','B','Answer: entrepreneurship');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Hagen identifies _____types of events that cover produce status withdrawal','multiple_choice','value','calculated','groups and families','four','D','Answer: four');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Status withdrawal is the perception on the part of the members of some ______that their purposes','multiple_choice','having inferiority or any other type of complex.','Economic','and value s on life are not respected by groups in the society whom they respect.','because of their ‗‘troubled childhood‘‘','C','Answer: and value s on life are not respected by groups in the society whom they respect.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to G.F. Papanek and J.R. Harris, ______ are the main drive for the entrepreneurial','multiple_choice','selfemployment of any sort','activities.','Every profession has its _____ .','performance improvement','B','Answer: activities.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ perceives entrepre neurship as involving "activities necessary to create or carry on an','multiple_choice','enterprise where not all markets are well established or clearly defined and/or in which relevant','the progression of distinct personality uniqueness and motivates people in the culture to utilize in','growth -orientation','particular economic conditions are most favourable.','A','Answer: enterprise where not all markets are well established or clearly defined and/or in which relevant');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to Jones, George and Hill (2000), _____is a manager, scientist, or researcher who','multiple_choice','works inside an existing organization and notices opportunities for product improvements and is','Sociologists','Entrepreneurs','Entrepreneurship','A','Answer: works inside an existing organization and notices opportunities for product improvements and is');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Sociological enterprise focuses on the _____ .','multiple_choice','social context','because of their ‗‘troubled childhood‘‘','having inferiority or any other type of complex.','and incentives in order to arrive at a risk -reward eq uation that informs a determination on','A','Answer: social context');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'In the early ______century the Frenchmen who organized and led military expeditions were','multiple_choice','other assets, introduces changes, innovations and new orders for profitable and rewarding ends.','growth -orientation','something, to realize his/her potential or to become his own boss.','referred to as ''Entrepreneurs''.','D','Answer: referred to as ''Entrepreneurs''.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The entrepreneur is a_____.','multiple_choice','way of the dinosaur.','go the way of the dinosaur.','life''s events are the result of external factors, such as chance, luck or fate','visionary','D','Answer: visionary');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ observes that scholars had not been in agreement in their definitions of entrepreneurship','multiple_choice','and chronicled the definitions of entrepreneurship by various scholars','members for performance improvement and excellence','markets.','corporate','A','Answer: and chronicled the definitions of entrepreneurship by various scholars');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'a way as to add______.','multiple_choice','economic system.','value','the progression of distinct personality uniqueness and motivates people in the culture to utilize in','An entrepreneur has _____ about the objectives to be achieved in the business, the nature of','B','Answer: value');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs have to recognize opportunities in the face of ______ and are willing to bear','multiple_choice','planning, investing in the future, and delaying gratification','uncertainty when exploiting opportunities','people','mobilize resources to meet it.','B','Answer: uncertainty when exploiting opportunities');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'inheritance of enterprise culture, social marginality and _____ .','multiple_choice','ethnicity','lack of understanding of how bus inesses are created','The need for achievement theory','having inferiority or any other type of complex.','A','Answer: ethnicity');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Sociologists argue that Entrepreneurship is most likely to emerge under a specific _____ .','multiple_choice','Putari','social culture','for the future, to be confident and aggressive (high growth orientation), having more plans and','corporate','B','Answer: social culture');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ views entrepreneurs as ind ividuals who attempt to predict and act upon change within','multiple_choice','risk','markets.','entrepreneurship','______ theory suggests that individuals who recognize a strong level of incongruence between','B','Answer: markets.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ is a hot slogan among corporate and entrepreneurial companies alike.','multiple_choice','Entrepreneurs','Culture','Kets de Vries','risk takers','B','Answer: Culture');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs are usually _____ , buoyant and highly self -motivated.','multiple_choice','passionate','capital','Status withdrawal','Intrepreneurs','A','Answer: passionate');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurship was looked as ______ activity.','multiple_choice','speculative','Every profession has its _____ .','employment as well as performance in self -employment.','uncertainty when exploitin g opportunities','A','Answer: speculative');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_____ and Austrian Market Process','multiple_choice','Neo-classical','______ was looked as speculative activity.','innovative manner to generate value to the customer with the hope that this value will exceed the','market -based systems','A','Answer: Neo-classical');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'situations where particular economic conditions are most _______ .','multiple_choice','employment as well as performance in self -employment.','the term in England.','entrepreneur','favourable','D','Answer: favourable');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs are usually passionate, ______ and highly self -motivated.','multiple_choice','buoyant','organizations','marginality and ethnicity.','life''s events are the result of external factors, such as chance, luck or fate','A','Answer: buoyant');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The _____ is the third of the major entrepreneurship theories.','multiple_choice','sociological theory','mobilize resources to meet it.','and other assets, introduces changes, innovations and new orders for profitable and rewarding','opportunities','A','Answer: sociological theory');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ measures the degree to which individuals express pride, loyalty and cohesiveness in the ir','multiple_choice','the progression of distinct personality uniqueness and motivates people in the culture to utilize in','innovative manner to generate value to the customer with the hope that this value will exceed the','ethnicity','groups and families','D','Answer: groups and families');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ theory explained that human beings have a need to succeed, accomplish, excel or achieve.','multiple_choice','applied it to a business context, while emphasizing the combination of resources.','and value s on life are not respected by groups in the society whom they respect.','The need for achievement theory','life''s events are the result of external factors, such as chance, luck or fate','C','Answer: The need for achievement theory');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs are usually passionate, buoyant and ______ .','multiple_choice','highly self -motivated','people','life''s events are the result of external factors, such as chance, luck or fate','in-group collectivism','A','Answer: highly self -motivated');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ is the processes and activities by which corporate organization behave entrepreneurially.','multiple_choice','Entrepreneurship','social system','the restrictions imposed by the value system governing the society.','and chronicled the definitions of entrepreneurship by various scholars','A','Answer: Entrepreneurship');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Though the precise meaning of Entrepreneur is the ‗undertaker of a project,‘ ______popularized','multiple_choice','French','life''s events are the result of external factors, such as chance, luck or fate','calculated','the term in England.','D','Answer: the term in England.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Every _____ has its culture.','multiple_choice','profession','and values on life are not respected by groups in the society whom they respect.','where particular economic conditions are most favourable.','applied it to a business context, while emphasizing the combination of resources.','A','Answer: profession');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs have to recognize ______ in the face of uncertainty and are willing to bear','multiple_choice','mobilize resources to meet it.','addition to the general framework.','uncertainty when exploitin g opportunities','companies','C','Answer: uncertainty when exploitin g opportunities');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Stoner et al., (2009) opined that in today‘s faced -paced economy, _____ that do not keep up may','multiple_choice','go the way of the dinosaur.','favourable','Cantillon (circa 1730)','feedback','A','Answer: go the way of the dinosaur.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The ______ is a visionary.','multiple_choice','success','entrepreneur','and entrepre neurial activities','factors that infuse the entrepreneurial spirit in an individual.','B','Answer: entrepreneur');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'accomplish something, to realize his/her potential or to become his own ______ .','multiple_choice','works inside an existing organization and notices opportunities for product improvements and is','factors that infuse the entrepreneurial spirit in an individual.','boss','shyness','C','Answer: boss');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneur perceives the market ______ and then has the motivation, drive and ability to','multiple_choice','culture','mobilize resources to meet it.','enterprise where not all markets are well established or clearly defined and/or in which relevant','through the carrying out of new combinations such as introduction of new techniques of','B','Answer: mobilize resources to meet it.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'members for perfo rmance improvement and ______','multiple_choice','and other assets, introduces changes, innovations and new orders for profitable and rewarding','excellence','planning, investing in the future, and delaying gratification','''Entrepreneurs''.','B','Answer: excellence');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneur and Entrepreneurship have been a point of interest to economics as early as______.','multiple_choice','Intrepreneurs','internal','three','1755','D','Answer: 1755');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to Sexton & Bowman (1986), ______ is a value in itself for Americans.','multiple_choice','in-group collectivism','entrepreneurship','mobilize resources to meet it.','1755','B','Answer: entrepreneurship');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______','multiple_choice','the setting in which they work','value','uncertainty when exploiting opportunities','and value s on life are not respected by groups in the society whom they respect.','A','Answer: the setting in which they work');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'include ______','multiple_choice','Ibos in Nigeria, Kikuyus in Kenya and Chagga in Tanzania','prices in order to combine them" into a new product','internal','self-confidence','A','Answer: Ibos in Nigeria, Kikuyus in Kenya and Chagga in Tanzania');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Future orientation is related to two, and at times competing, ______ .','multiple_choice','______ theory suggests that individuals who recognize a strong level of incongruence between','orientations','particular economic conditions are most favourable.','because of their ‗‘troubled childhood‘‘','B','Answer: orientations');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs often strive to achieve _____ tasks.','multiple_choice','challenging','other assets, introduces changes, innovations and new orders for profitable and rewarding ends.','and values on life are not respected by groups in the society whom they respect.','entreprendre','A','Answer: challenging');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'and as such has  to work in an organization. In this case they are referred to as _______','multiple_choice','entrepreneurship','buoyant','Intrepreneurs','gathering the necessary resources to take advantage of them and initiate appropriate action to','C','Answer: Intrepreneurs');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurship is inhibited by the_____, which denies opportunities for creative facilities','multiple_choice','personal attributes','social system','______ studies found indirect support for a negative relationship between uncertainty avoidance','prices in order to combine them" into a new product','B','Answer: social system');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Classical theorists articulated three modes of production: ______ ; capital; and labour.','multiple_choice','''Entrepreneurs''.','land','______ studies found indirect support for a negative relationship between uncertainty avoidance','the only way to be indep endent is to be an entrepreneur','B','Answer: land');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The AMP, a model influenced by ______','multiple_choice','something, to realize his/her potential or to become his own boss.','Joseph Aloi Schumpeter','withdrawal of status','community be it a business community, a cultural (or ethnic) community, a country, or a','B','Answer: Joseph Aloi Schumpeter');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'People who are success in business are moderate _____ .','multiple_choice','opportunism','risk takers','resources to meet it.','labour','B','Answer: risk takers');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'In the early 18th century French economist ______ used the term entrepreneur to business.','multiple_choice','Richard Cantillon','internal','_______ argue that Entrepreneurship is most likely to emerge under a specific social culture.','markets.','A','Answer: Richard Cantillon');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ is the perception on the part of the  members of some social group that their purposes','multiple_choice','depict the behaviour of certain group or people.','way of the dinosaur.','and values on life are not respected by groups in the society whom they respect.','risks','C','Answer: and values on life are not respected by groups in the society whom they respect.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Power distance can affect entrepreneurial  activity positively because _______','multiple_choice','visionary','hot slogan','risk takers','the only way to be indep endent is to be an entrepreneur','D','Answer: the only way to be indep endent is to be an entrepreneur');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'became known as the_____.','multiple_choice','Cantillon','self-confidence','prices in order to combine them" into a new product','Austrian Market process (AMP)','D','Answer: Austrian Market process (AMP)');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'An entrepreneur must have a good _____system.','multiple_choice','and other assets, introduces changes, innovations and new orders for profitable and rewarding','driven entrepreneurs during the early age of Reform and Opening Up.','feedback','entrepreneurial activities.','C','Answer: feedback');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The word "Entrepreneur" is derived from the Fren ch verb _____','multiple_choice','entrepredre','opportunities','slogan','groups and families','A','Answer: entrepredre');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneur perceives the market opportunity and then has the motivation, ______ and ability to','multiple_choice','Austrian Market process (AMP)','and chronicled the definitions of entrepreneurship by various scholars','mobilize resources to meet it.','uncertainty when exploiting opportunities','C','Answer: mobilize resources to meet it.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'referred to as ______','multiple_choice','Locus of control was first introduced by Julian Rotter in the ______','Ibos in Nigeria, Kikuyus in Kenya and Chagga in Tanzania','Entrepreneurs','referred to as ''Entrepreneurs''.','C','Answer: Entrepreneurs');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Classical theorists articulated three modes of production: land; capital; and ____ __.','multiple_choice','labour','Cantillon (circa 1730)','Entrepreneurship','risks','A','Answer: labour');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'calculated _____ .','multiple_choice','Neo-classical','internal','skills without incurring the risks associated with those activities','risks','D','Answer: risks');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Psychological theory of entrepreneurship identifies traits, ______ and personalities as the major','multiple_choice','profession','factors that infuse the entrepreneurial spirit in an individual.','for the future, to be confident and aggressive (high growth orientation), having more plans and','applied it to a business context, while emphasizing the combination of resources.','B','Answer: factors that infuse the entrepreneurial spirit in an individual.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The _____ of entrepreneurship embraces social culture as a driving force of entre preneurship.','multiple_choice','sociological theory','innovative manner to generate value to the customer with the hope that this value will exceed the','social culture','ethnicity','A','Answer: sociological theory');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ refers to all the processes and activities involved in establishing, nurturing, and sustaining','multiple_choice','a business enterprise.','entrepreneurs from unsuccessful ones.','resources','______ conceives entrepreneurship as the creation of new organizations.','A','Answer: a business enterprise.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ is the fundamental mechanism of principles linking to a specific community, and builds','multiple_choice','Kets de Vries','innovation strategy.','competing','the progression of distinct personality uniqueness and motivates people in the culture to utilize in','D','Answer: the progression of distinct personality uniqueness and motivates people in the culture to utilize in');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs often strive to ______ challenging tasks.','multiple_choice','prices in order to combine them" into a new product','and chronicled the definitions of entrepreneurship by various scholars','achieve','a business enterprise.','C','Answer: achieve');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to ______ , entrepreneurship and economic growth will take place in those situations','multiple_choice','social system','factors that infuse the entrepreneurial spirit in an individual.','where particular economic conditions are most favourable.','innovative manner to generate value to the customer with the hope that this value will exceed the','C','Answer: where particular economic conditions are most favourable.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Classical theorists articulated three modes of production: land; _____ ; and labour.','multiple_choice','in-group collectivism','capital','''Entrepreneurs''.','the setting in which they work','B','Answer: capital');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'In _____ , the harsh system of HuJi (Household registration) produces a great deal of necessity','multiple_choice','value','Economic incentives','companies','driven entrepreneurs during the early age of Reform and Opening Up.','D','Answer: driven entrepreneurs during the early age of Reform and Opening Up.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Cantillon (circa 17 30) views entrepreneurship as: ______','multiple_choice','events in his/her life.','Every profession has its _____ .','selfemployment of any sort','having inferiority or any other type of complex.','C','Answer: selfemployment of any sort');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ are the major drive for the entrepreneurial activities.','multiple_choice','Economic incentives','go the way of the dinosaur.','risks','French','A','Answer: Economic incentives');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Individual with an external locus of control believe that ______','multiple_choice','life''s events are the result of external factors, such as chance, luck or fate','events in his/her life.','labour','activities.','A','Answer: life''s events are the result of external factors, such as chance, luck or fate');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Sociological models that have received signif icant empirical support are ______','multiple_choice','performance improvement and excellence.','events in his/her life.','and entrepre neurial activities','intergeneration inheritance of enterprise culture, social margina lity and ethnicity','D','Answer: intergeneration inheritance of enterprise culture, social margina lity and ethnicity');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'mainly_____, personal attributes and traits.','multiple_choice','employment as well as performance in self -employment.','have to be acquired (hard skills).','internal','mobilize resources to meet it.','C','Answer: internal');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ incentives are the major drive for the entrepreneurial a ctivities.','multiple_choice','Economic','driver','the only way to be indep endent is to be an entrepreneur','through new combinations of its existing resources.','A','Answer: Economic');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The word entrepreneurship stems from the ______ word','multiple_choice','Neo-classical','depict the behaviour of certain group or people.','Economic','French','D','Answer: French');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The ______ school of entrepreneurship considers the relationship between economic conditions','multiple_choice','Environmental factors','and incentives in order to arrive at a risk -reward eq uation that informs a determination on','go the way of the dinosaur.','the restrictions imposed by the value system governing the society.','B','Answer: and incentives in order to arrive at a risk -reward eq uation that informs a determination on');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The ______ model emerged from the criticisms of the classical model and indicated that','multiple_choice','economic phenomena could be relegated to instances of pure exchange, reflect an optimal ratio,','be an entrepreneur.','Entrepreneurs','particular economic conditions are most favourable.','A','Answer: economic phenomena could be relegated to instances of pure exchange, reflect an optimal ratio,');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'A _____ point of view may be that: an entrepreneur is someone who feels the need to accomplish','multiple_choice','the only way to be indep endent is to be an entrepreneur','that infuse the entrepreneurial spirit in an individual.','something, to realize his/her potential or to become his own boss.','addition to the general framework.','C','Answer: something, to realize his/her potential or to become his own boss.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ theory suggests that individuals who recognize a strong level of incongruence between','multiple_choice','their personal attributes and the role they hold in society will be motivated to change or','activities.','where particular economic conditions are most favourable.','business enterprise','A','Answer: their personal attributes and the role they hold in society will be motivated to change or');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Sociologists argue that Entrepreneurship is most likely to emerge under a specific social _____ .','multiple_choice','culture','groups and families','Entrepreneurs','Richard Cantillon','A','Answer: culture');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'uncertainty when exploiting _______','multiple_choice','Britain‗s industrial revolution which took place in the mid -1700 and lasted until the 1830s.','opportunities','culture','corporate','B','Answer: opportunities');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'which depict the behaviour of certain group or ______ .','multiple_choice','people','and entrepre neurial activities','that infuse the entrepreneurial spirit in an individual.','feedback','A','Answer: people');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ is the process whereby an organization seeks to expand by exploring new opportunities','multiple_choice','through new combinations of its existing resources.','competing','success','shyness','A','Answer: through new combinations of its existing resources.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ is an important characteristic that enables individuals to handle any situation without','multiple_choice','performance improvement','having inferiority or any other type of complex.','market -based systems','way of the dinosaur.','B','Answer: having inferiority or any other type of complex.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ views entrepreneurship as the activity that involves identifying opportunities within the','multiple_choice','people','economic system.','corporate entrepreneurship','Culture','B','Answer: economic system.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ theory of entrepreneurship identifies traits, motives and personalities as the major factors','multiple_choice','______ conceives entrepreneurship as the creation of new organizations.','economic phenomena could be relegated to instances of pure exchange, reflect an optimal ratio,','that infuse the entrepreneurial spirit in an individual.','Culture','C','Answer: that infuse the entrepreneurial spirit in an individual.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Hagen considers _____respect as the trigger mechanism for changes in personality formation','multiple_choice','risk','Neo-classical','cool, calm and collected','withdrawal of status','D','Answer: withdrawal of status');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Modernistic  cultures are more consistent with the two essences of entrepreneurship: _____ and','multiple_choice','growth -orientation.','community be it a business community, a cultural (or ethnic) community, a country, or a','Classical theorists','groups and families','A','Answer: growth -orientation.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Successful entrepreneurs have the creative ability to recognize and pursue______.','multiple_choice','opportunities','other assets, introduces changes, innovations and new orders for profitable and rewarding ends.','the term in England.','uncertainty when exploiting opportunities','A','Answer: opportunities');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Sociologists argue that ______ is most likely to emerge under a specific social culture.','multiple_choice','intergeneration inheritance of enterprise culture, social margina lity and ethnicity','four','Entrepreneurship','risks','C','Answer: Entrepreneurship');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'members for _____and excellence','multiple_choice','risk','shyness','______ theory suggests that individuals who recognize a strong level of incongruence between','performance improvement','D','Answer: performance improvement');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ showed that individualism should influence the type, rather than the absolute levels, of','multiple_choice','tasks','referred to as ''Entrepreneurs''.','internal','innovation strategy.','D','Answer: innovation strategy.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Psychological theory of entrepreneurship identifies traits, motives and ______ as the major factors','multiple_choice','companies','that infuse the entrepreneurial spirit in an individual.','Kets de Vries','for the future, to be confident and aggressive (high growth orientation), having more plans and','B','Answer: that infuse the entrepreneurial spirit in an individual.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'sustaining a _____ .','multiple_choice','Sociologists','entrepreneur','business enterprise','skills without incurring the risks associated with those activities','C','Answer: business enterprise');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Reynolds (1991) identified ______ social contexts that relates to entrepreneurial opportunity.','multiple_choice','and chronicled the definitions of entrepreneurship by various scholars','four','David Mc Clelland (1961)','entreprendre','B','Answer: four');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneur perceives the ______ and then has the motivation, drive and ability to mobilize','multiple_choice','they are able to control life events','works inside an existing organization and notices opportunities for product improvements and is','resources to meet it.','Locus of control','C','Answer: resources to meet it.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Schumpeter (1934) described entrepreneurship as a driver of ______ .','multiple_choice','social culture','collectivistic societies provide mo re social support and resources','market -based systems','French','C','Answer: market -based systems');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ perceives the market opportunity and then has the motivation, drive and ability to','multiple_choice','''Entrepreneurs''.','Austrian Market process (AMP)','Entrepreneurship','mobilize resources to meet it.','D','Answer: mobilize resources to meet it.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Collectivism helps entrepreneurship because ______','multiple_choice','works inside an existing organization and notices opportunities for product improvements and is','be unequally distributed','collectivistic societies provide mo re social support and resources','resources to meet it.','C','Answer: collectivistic societies provide mo re social support and resources');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ attributes differentiate entrepreneurs from non -entrepreneurs, and successful','multiple_choice','Every profession has its _____ .','entrepreneurs from unsuccessful ones.','self-confidence','G.F. Papanek and J.R. Harris','B','Answer: entrepreneurs from unsuccessful ones.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_____ have to recognize opportunities in the face of uncertainty and are willing to bear','multiple_choice','challenging','mobilize resources to meet it.','Schumpeter (1934)','uncertainty when exploiting opportunities','D','Answer: uncertainty when exploiting opportunities');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ conceives the entrepreneur as the innovator who implements change within markets','multiple_choice','Economic','through the carrying out of new combinations such as introduction of new techniques of','Entrepreneurship','having inferiority or any other type of complex.','B','Answer: through the carrying out of new combinations such as introduction of new techniques of');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ encourage people to achieve high performance and to be unique (innovation), to invest','multiple_choice','for the future, to be confident and aggressive (high growth orientation), having more plans and','particular economic conditions are most favourable.','orientations','Culture','A','Answer: for the future, to be confident and aggressive (high growth orientation), having more plans and');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'and______ .','multiple_choice','skills without incurring the risks associated with those activities','the restrictions imposed by the value system governing the society.','social system','growth -orientation','D','Answer: growth -orientation');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ articulated three modes of production: land; capital; and labour.','multiple_choice','excellence','autonomy, creativity and sense of responsibility (soft skills) and so on.','Classical theorists','Sociologists','C','Answer: Classical theorists');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to David Mc Clelland (1961), an entrepreneur is a ______ person who takes calculated','multiple_choice','______ theory suggests that individuals who recognize a strong level of incongruence between','third','risks.','their personal attributes and the role they hold in society will be motivated to change or','C','Answer: risks.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ described entrepreneurship as a driver of market -based systems.','multiple_choice','Austrian Market Process','1755','Schumpeter (1934)','entrepreneurship','C','Answer: Schumpeter (1934)');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to Sexton & Bowman (1986), entrepreneurship is a ______ in itself for Americans.','multiple_choice','value','particular economic conditions are most favourable.','mobilize resources to meet it.','something, to realize his/her potential or to become his own boss.','A','Answer: value');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'mobilize ______ to meet it.','multiple_choice','selfemployment of any sort','Entrepreneurs','resources','addition to the general framework.','C','Answer: resources');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to ______ , entrepreneurship is a value in itself for Americans.','multiple_choice','value','Sexton & Bowman (1986)','particular economic conditions are most favourable.','activities.','B','Answer: Sexton & Bowman (1986)');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Culture is a hot slogan among ______and entrepreneurial companies alike.','multiple_choice','Richard Cantillon','responsibility and a desire for a concrete measure of task performance.','and entrepre neurial activities','corporate','D','Answer: corporate');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'AMP stands for_______','multiple_choice','third','Environmental factors','Austrian Market Process','depict the behaviour of certain group or people.','C','Answer: Austrian Market Process');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The economic school is subdivided into the ______,______, and ______ which serves an','multiple_choice','addition to the general framework.','three','_______ argue that Entrepreneurship is most likely to emerge under a specific social culture.','selfemployment of any sort','A','Answer: addition to the general framework.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to _____ , an entrepreneur is a dynamic person who takes calculated risks.','multiple_choice','risks','orientations','sociological theory','David Mc Clelland (1961)','D','Answer: David Mc Clelland (1961)');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Modernistic  cultures are more consistent with the ______ essences of entrepreneurship','multiple_choice','and chronicled the definitions of entrepreneurship by various scholars','four','orientations','two','D','Answer: two');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'not______.','multiple_choice','for the future, to be confident and aggressive (high growth orientation), having more plans and','resources to meet it.','and chronicled the definitions of entrepreneurship by various scholars','opportunism','D','Answer: opportunism');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ play a vital role in the survival of businesses.','multiple_choice','Environmental factors','Britain‗s industrial revolution which took place in the mid -1700 and lasted until the 1830s.','hot slogan','tasks','A','Answer: Environmental factors');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ focuses on the social context.','multiple_choice','Sociological enterprise','risk takers','competing','something, to realize his/her potential or to become his own boss.','A','Answer: Sociological enterprise');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ can be defined as the mix of norms, values and beliefs that are shared by a particular','multiple_choice','gathering the necessary resources to take advantage of them and initiate appropriate action to','enterprise where not all markets are well established or clearly defined and/or in which relevant','be unequally distributed','community be it a business community, a cultural (or ethnic) community, a country, or a','D','Answer: community be it a business community, a cultural (or ethnic) community, a country, or a');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneur perceives the market opportunity and then has the _____ , drive and ability to','multiple_choice','Locus of control was first introduced by Julian Rotter in the ______','referred to as ''Entrepreneurs''.','success','mobilize resources to meet it.','D','Answer: mobilize resources to meet it.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Rotter (1966) refers to ______ as an individual‗s perception about the underlying main causes of','multiple_choice','Stephenson (2010) believes that entre preneurial characteristics are','go the way of the dinosaur.','Classical theorists','events in his/her life.','D','Answer: events in his/her life.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'ILO stands for______','multiple_choice','the restrictions imposed by the value system governing the society.','Britain‗s industrial revolution which took place in the mid -1700 and lasted until the 1830s.','culture','Intended Learning Outcomes','D','Answer: Intended Learning Outcomes');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Every activity carried out by _____ is surrounded by ce rtain cultural values and ethics which','multiple_choice','Culture','depict the behaviour of certain group or people.','capital','lack of understanding of how bus inesses are created','B','Answer: depict the behaviour of certain group or people.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ refers to the extent to which a society encourages and rewards its members for','multiple_choice','growth -orientation.','addition to the general framework.','performance improvement and excellence.','groups and families','C','Answer: performance improvement and excellence.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Future orientation is related to two, and at times______, orientations.','multiple_choice','competing','Intrepreneurs','their personal attributes and the role they hold in society will be motivated to change or','third','A','Answer: competing');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'In the early 16th century the _____who organized and led military expeditions were referred to as','multiple_choice','''Entrepreneurs''.','entrepreneur','opportunities','entrepredre','A','Answer: ''Entrepreneurs''.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to McClelland, it is the high need for _____ which drives people towards','multiple_choice','challenging tasks','planning, investing in the future, and delaying gratification','Cantillon (circa 1730)','entrepreneurial activities.','D','Answer: entrepreneurial activities.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The ______ theory inscribed the virtues of free trade, specialization which was a result of','multiple_choice','having inferiority or any other type of complex.','Every profession has its _____ .','gathering the necessary resources to take advantage of them and initiate appropriate action to','Britain‗s industrial revolution which took place in the mid -1700 and lasted until the 1830s.','D','Answer: Britain‗s industrial revolution which took place in the mid -1700 and lasted until the 1830s.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Societies with a high level of ______ make greater distinctions between in -group and out -group','multiple_choice','visionary','challenging tasks','in-group collectivism','social context','C','Answer: in-group collectivism');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Individuals with an ______ locus of contr ol believe that they are able to control life events','multiple_choice','value','internal','Entrepreneurs','Cantillon','B','Answer: internal');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Every profession has its _____ .','multiple_choice','sociological theory','autonomy, creativity and sense of responsibility (soft skills) and so on.','excellence','culture','D','Answer: culture');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Culture is a hot _____ among corporate and entrepreneurial companies alike.','multiple_choice','resources to meet it.','slogan','value','employment as well as performance in self -employment.','B','Answer: slogan');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'In_______, the entrepreneur is defined as one who combines various input factors in an','multiple_choice','innovative manner to generate value to the customer with the hope that this value will exceed the','Neo-classical','achieve','highly self -motivated','A','Answer: innovative manner to generate value to the customer with the hope that this value will exceed the');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs need to be  cool, calm and ______ .','multiple_choice','collected','mobilize resources to meet it.','groups and families','uncertainty when exploiting opportunities','A','Answer: collected');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs need to be _____ , calm and collected.','multiple_choice','cool','Economic','challenging tasks','ethnicity','A','Answer: cool');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'assume_______.','multiple_choice','Schumpeter (1934)','shyness','value','risk','D','Answer: risk');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ refers to attitudes and values which in the case of entrepreneurship may be linked with','multiple_choice','particular economic conditions are most favourable.','autonomy, creativity and sense of responsibility (soft skills) and so on.','classical school, neo -classical and Austrian process market','gathering the necessary resources to take advantage of them and initiate appropriate action to','B','Answer: autonomy, creativity and sense of responsibility (soft skills) and so on.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs often strive to achieve ______ .','multiple_choice','challenging tasks','addition to the general framework.','internal','land','A','Answer: challenging tasks');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Schumpeter (1934) described entrepreneurship as a ______ of market -based systems.','multiple_choice','uncertainty when exploitin g opportunities','referred to as ''Entrepreneurs''.','driver','Cantillon (circa 1730)','C','Answer: driver');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'_______ argue that Entrepreneurship is most likely to emerge under a specific social culture.','multiple_choice','internal','entrepreneurship','Sociologists','culture','C','Answer: Sociologists');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to economists, ______ and economic growth will take place in those situations where','multiple_choice','skills without incurring the risks associated with those activities','particular economic conditions are most favourable.','risks','go the way of the dinosaur.','B','Answer: particular economic conditions are most favourable.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'mainly internal, ______ and traits.','multiple_choice','feedback','entrepreneur','personal attributes','corporate','C','Answer: personal attributes');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The ______sees an entrepreneur as someone who combines resources such as labour, materials','multiple_choice','entrepreneurial activities.','and other assets, introduces changes, innovations and new orders for profitable and rewarding','Intended Learning Outcomes','they are able to control life events','B','Answer: and other assets, introduces changes, innovations and new orders for profitable and rewarding');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ origin of a person is said to influence the choice between paid employment and self -','multiple_choice','Richard Cantillon','Schumpeter (1934)','particular economic conditions are most favourable.','employment as well as performance in self -employment.','D','Answer: employment as well as performance in self -employment.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Classical theorists articulated _____ modes of production','multiple_choice','through the carrying out of new combinations such as introduction of new techniques of','economic phenomena could be relegated to instances of pure exchange, reflect an optimal ratio,','entrepreneurial activities.','three','D','Answer: three');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Psycho -dynamic Model was propounded by ______.','multiple_choice','factors that infuse the entrepreneurial spirit in an individual.','Austrian Market Process','motivation','Kets de Vries','D','Answer: Kets de Vries');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'______ are usually not completely part of the society of their adoption as such; they are free of','multiple_choice','the restrictions imposed by the value system governing the society.','employment as well as performance in self -employment.','three','collected','A','Answer: the restrictions imposed by the value system governing the society.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Individuals with high _____ tend to take keen interest in situations of high rest, desire for','multiple_choice','four','entrepreneurial activities.','responsibility and a desire for a concrete measure of task performance.','selfemployment of any sort','C','Answer: responsibility and a desire for a concrete measure of task performance.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Intrapreneurship is also called_____','multiple_choice','risks','corporate entrepreneurship','Cantillon','speculative','B','Answer: corporate entrepreneurship');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Culture is a ______among corporate and entrepreneurial companies alike.','multiple_choice','through new combinations of its existing resources.','driver','tasks','hot slogan','D','Answer: hot slogan');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Performance orientation refers to the extent to which a ______ encourages and rewards its','multiple_choice','Stephenson (2010) believes that entre preneurial characteristics are','entrepreneurship','members for performance improvement and excellence','French','C','Answer: members for performance improvement and excellence');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'Individuals with an internal locus of control believe that_______','multiple_choice','something, to realize his/her potential or to become his own boss.','they are able to control life events','personal attributes','excellence','B','Answer: they are able to control life events');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'According to economists, entrepreneurship and ______ will take place in those situations where','multiple_choice','particular economic conditions are most favourable.','emotional stability, good inter - personal relations, consideration and tactfulness','resources','______ theory suggests that individuals who recognize a strong level of incongruence between','A','Answer: particular economic conditions are most favourable.');
INSERT INTO questions (course_id,question_text,question_type,option_a,option_b,option_c,option_d,correct_answer,explanation)
VALUES (v_course_id,'The entrepreneur must have _____ and believe in him/herself.','multiple_choice','ethnicity','sociological theory','self-confidence','members for performance improvement and excellence','C','Answer: self-confidence');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'______ regards entrepreneurship as a process of seeing and evaluating business opport unities,','fill_in_blank','gathering the necessary resources to take advantage of them and initiate appropriate action to','Answer: gathering the necessary resources to take advantage of them and initiate appropriate action to');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'______ is an inside entrepreneur, or an entrepreneur within a large firm, who uses entrepreneurial','fill_in_blank','skills without incurring the risks associated with those activities','Answer: skills without incurring the risks associated with those activities');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'_______  refers to entrepreneurial knowledge and skills and management compet encies which','fill_in_blank','have to be acquired (hard skills).','Answer: have to be acquired (hard skills).');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'The word entrepreneurs hip stems from the French word ______','fill_in_blank','entreprendre','Answer: entreprendre');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'______ opined that in today‘s faced -paced economy, companies that do not keep up may go the','fill_in_blank','way of the dinosaur.','Answer: way of the dinosaur.');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'______ views entrepreneurs as change agents','fill_in_blank','Putari','Answer: Putari');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'_______ addresses the degree to which individuals engage in future  oriented behaviours such as','fill_in_blank','planning, investing in the future, and delaying gratification','Answer: planning, investing in the future, and delaying gratification');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'______ studies found indirect support for a negative relationship between uncertainty avoidance','fill_in_blank','and entrepre neurial activities','Answer: and entrepre neurial activities');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'People who are ______ in business are moderate risk takers.','fill_in_blank','success','Answer: success');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'______ conceptualized the entrepreneur as: the "agent who buys means of production at certain','fill_in_blank','prices in order to combine them" into a new product','Answer: prices in order to combine them" into a new product');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'In the early 18th century French economist Richard _____ used the term entrepreneur to busi ness.','fill_in_blank','Cantillon','Answer: Cantillon');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'Psychological theory of entrepreneurship identifies ______ , motives and personalities as the major','fill_in_blank','factors that infuse the entrepreneurial spirit in an individual.','Answer: factors that infuse the entrepreneurial spirit in an individual.');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'Gartner (1988) conceives entrepreneurship as the creation of new ______ .','fill_in_blank','organizations','Answer: organizations');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'because of _______','fill_in_blank','lack of understanding of how bus inesses are created','Answer: lack of understanding of how bus inesses are created');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs need to be _______','fill_in_blank','cool, calm and collected','Answer: cool, calm and collected');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'include_______','fill_in_blank','emotional stability, good inter - personal relations, consideration and tactfulness','Answer: emotional stability, good inter - personal relations, consideration and tactfulness');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'The economist sees ______ as someone who combines resources such as labour, materials and','fill_in_blank','other assets, introduces changes, innovations and new orders for profitable and rewarding ends.','Answer: other assets, introduces changes, innovations and new orders for profitable and rewarding ends.');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'_______ views entrepreneurship as: ―selfemployment of any sort‖.','fill_in_blank','Cantillon (circa 1730)','Answer: Cantillon (circa 1730)');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'An entrepreneurial ______ is what many companies hope for.','fill_in_blank','culture','Answer: culture');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'In______ , Joseph Schumpeter equated entrepreneurship with the concept of innovation and','fill_in_blank','applied it to a business context, while emphasizing the combination of resources.','Answer: applied it to a business context, while emphasizing the combination of resources.');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'_______ are usually passionate, buoyant and highly self -motivated.','fill_in_blank','Entrepreneurs','Answer: Entrepreneurs');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'Intrapreneurs can be identified through many traits, including all of these EXCEPT _____.','fill_in_blank','shyness','Answer: shyness');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'_______ model is concerned with how people tend to be self -employed and beco me successful','fill_in_blank','because of their ‗‘troubled childhood‘‘','Answer: because of their ‗‘troubled childhood‘‘');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'An _____ of a person is said to influence the choice between paid employment and self -','fill_in_blank','employment as well as performance in self -employment.','Answer: employment as well as performance in self -employment.');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'_______ measures the degree to which members of a society expect and agree that power should','fill_in_blank','be unequally distributed','Answer: be unequally distributed');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'Entrepreneurs within an organization are called______','fill_in_blank','Intrepreneurs','Answer: Intrepreneurs');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'_____ risks.','fill_in_blank','calculated','Answer: calculated');
INSERT INTO questions (course_id,question_text,question_type,correct_answer,explanation)
VALUES (v_course_id,'Sociological models that have received significant empirical support are the _____ , social','fill_in_blank','marginality and ethnicity.','Answer: marginality and ethnicity.');
END $$;