DO $$
DECLARE
    v_course_id UUID;
BEGIN
    SELECT id INTO v_course_id FROM courses WHERE code = 'POL228' LIMIT 1;

    -- Multiple choice questions (85% - 85 questions)
    INSERT INTO questions (course_id, question_text, question_type, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
    (v_course_id, 'In comparative analysis, ____ is used to interrogate whether or not the measurements used in a given research are properly operationalized', 'multiple_choice', 'External validity', 'Internal validity', 'Reliability', 'Objectivity', 'B', 'Internal validity assesses whether measurements properly capture the intended concepts.'),
    (v_course_id, 'As an approach to the study of politics, the scientific approach introduced two major elements; and this are, emphasis on ____, and on the individual as the central unit of political analysis', 'multiple_choice', 'Scientific method', 'Historical analysis', 'Philosophical reasoning', 'Case studies', 'A', 'The scientific approach emphasizes systematic methodology and individual-level analysis.'),
    (v_course_id, 'David Easton insists that post behavioralism should be backed by ____ and ____', 'multiple_choice', 'Action and Relevance', 'Theory and Practice', 'Data and Analysis', 'Politics and Science', 'A', 'Easton argued post-behavioralism should focus on action and relevance to real-world problems.'),
    (v_course_id, 'Comparative politics relies on the method of ___, and method of "agreement"', 'multiple_choice', 'Difference', 'Similarity', 'Correlation', 'Causation', 'A', 'J.S. Mill''s methods of difference and agreement are fundamental to comparative analysis.'),
    (v_course_id, 'The two main comparative approaches for choosing cases are: ____, and most different systems (MDS)', 'multiple_choice', 'Most Similar System (MSS)', 'Single Case Study', 'Cross-national Analysis', 'Historical Comparison', 'A', 'Most Similar Systems design compares cases that share many characteristics.'),
    (v_course_id, 'The discipline of comparative politics has undergone three key changes, and this includes; ____, object of inquiry, method of deploying data', 'multiple_choice', 'Theoretical frameworks', 'Empirical findings', 'Research methods', 'Political ideologies', 'B', 'Comparative politics has evolved in its empirical findings, objects of study, and data methods.'),
    (v_course_id, 'The simultaneous study of a large number of nation-states in comparative studies is referred to as --------------', 'multiple_choice', 'Case study method', 'The cross-national approach', 'Historical analysis', 'Qualitative research', 'B', 'Cross-national approach involves comparing multiple countries simultaneously.'),
    (v_course_id, 'One of the goals of the exploratory research method is to prove that ____', 'multiple_choice', 'Hypotheses are true', 'Further investigation is necessary', 'Theories are complete', 'Methods are perfect', 'B', 'Exploratory research often identifies areas needing further study.'),
    (v_course_id, 'A key feature of the Quantitative research method, is that data gathered are analyzed ______', 'multiple_choice', 'Qualitatively', 'Narratively', 'Numerically', 'Historically', 'C', 'Quantitative research uses numerical data and statistical analysis.'),
    (v_course_id, 'In the field of comparative politics, the term politics have three meanings, and this includes; politics as a political activity, ____, and a political process', 'multiple_choice', 'Political power', 'Political theory', 'Political science', 'Political history', 'A', 'Politics can be understood as activity, power, and process.'),
    (v_course_id, 'Systems theory is of great relevance in political Analysis because it does not only, ____, but also encourages the evaluation of the various patterns and levels of relationship amongst different units', 'multiple_choice', 'Ignore external factors', 'Identify the component units in a system', 'Focus only on outputs', 'Eliminate variables', 'B', 'Systems theory identifies components and their interrelationships within political systems.'),
    (v_course_id, 'The three primary components of every political system include the ____ ; the regime; and the authorities', 'multiple_choice', 'Political community', 'Economic system', 'Social structure', 'Cultural norms', 'A', 'Easton identified political community, regime, and authorities as system components.'),
    (v_course_id, 'The Input – Output model of David Easton explains the behaviour of ____ as well as the environment in a particular system', 'multiple_choice', 'Political System', 'Economic System', 'Social System', 'Cultural System', 'A', 'Easton''s model analyzes how political systems process inputs into outputs.'),
    (v_course_id, 'In Duverger''s law, an electoral system based on ____, tend to produce two parties', 'multiple_choice', 'Proportional representation', 'Single member district', 'Mixed system', 'Party list', 'B', 'Duverger''s law states single-member districts tend toward two-party systems.'),
    (v_course_id, 'In its developmental phases, the ____ period marked the rebirth of comparative politics', 'multiple_choice', 'Ancient', 'Medieval', 'Renaissance', 'Modern', 'C', 'The Renaissance period revived comparative political studies after the Middle Ages.'),
    (v_course_id, 'The system theory resonated as a result of the movement to unite ____, and scientific analysis', 'multiple_choice', 'Philosophy', 'Science', 'History', 'Economics', 'B', 'Systems theory integrated scientific analysis with political study.'),
    (v_course_id, 'Considered as one of the sub disciplines of Political Science, the goal of comparative politics is to understand, and ____ the nature of political power and interactions among nations', 'multiple_choice', 'Ignore', 'Explain', 'Complicate', 'Simplify', 'B', 'Comparative politics aims to understand and explain political power dynamics.'),
    (v_course_id, 'Though it originated among the Anthropologists and Sociologists, ____ adopted the concept of structural functionalism in political Analysis', 'multiple_choice', 'Karl Marx', 'Gabriel Almond', 'David Easton', 'Max Weber', 'B', 'Gabriel Almond adapted structural-functionalism for political science.'),
    (v_course_id, 'More often referred to as the "master strategy", the comparative approach is used in ____ about a specific case study', 'multiple_choice', 'Ignoring context', 'Drawing inferences', 'Eliminating variables', 'Simplifying complexity', 'B', 'Comparative method helps draw broader inferences from specific cases.'),
    (v_course_id, 'In political inquiry, ____ rely on the use of observation and measurement', 'multiple_choice', 'Normative approach', 'Empirical approach', 'Philosophical approach', 'Historical approach', 'B', 'Empirical approaches emphasize observation and measurement.'),
    (v_course_id, 'The output function in a system theory is performed by ____, according to Gabriel Almond', 'multiple_choice', 'Legislature', 'Executive', 'Judiciary', 'Political parties', 'B', 'Almond identified the executive as performing output functions in political systems.'),
    (v_course_id, 'The ____ theory help political scientists to understand how democracy is supposed to work in principle, and how they work in practice', 'multiple_choice', 'Authoritarian', 'Democratic', 'Socialist', 'Communist', 'B', 'Democratic theory examines both ideal and actual democratic functioning.'),
    (v_course_id, 'The ____ focuses on philosophy, values and norms in carrying out political Analysis', 'multiple_choice', 'Empirical Approach', 'Normative Approach', 'Scientific Approach', 'Behavioral Approach', 'B', 'Normative approach emphasizes values, ethics, and philosophical principles.'),
    (v_course_id, 'Logic as a concept dates back to the writings of ____, who established it in philosophy', 'multiple_choice', 'Plato', 'Aristotle', 'Socrates', 'Descartes', 'B', 'Aristotle is considered the founder of formal logic.'),
    (v_course_id, 'The error of explaining something in terms of one sole cause when other causes could also be at work is referred to as ________', 'multiple_choice', 'Reductivism', 'Holism', 'Pluralism', 'Complexity', 'A', 'Reductivism oversimplifies by attributing outcomes to single causes.'),
    (v_course_id, 'The formal systematic study of the principles of valid inference and correct reasoning is called _____________', 'multiple_choice', 'Epistemology', 'Logic', 'Methodology', 'Ontology', 'B', 'Logic is the study of valid reasoning and inference.'),
    (v_course_id, 'In the Aristotle classification of regimes, the good types include monarchy, aristocracy, and ____', 'multiple_choice', 'Tyranny', 'Polity', 'Oligarchy', 'Democracy', 'B', 'Aristotle classified polity as a good form of government by the many.'),
    (v_course_id, 'According to Arend Lijphart, the discussion of the comparative method is not complete without giving a consideration to the _________', 'multiple_choice', 'Statistical Analysis', 'Case Study Method', 'Historical Method', 'Experimental Method', 'B', 'Lijphart emphasized the importance of case study methods in comparative politics.'),
    (v_course_id, 'According to Landman (2008), the comparative study of institutional designs involves three types of institutions, and this includes; executive, legislative arrangements, ____, as well as the political party system', 'multiple_choice', 'The electoral system', 'The judicial system', 'The bureaucracy', 'The military', 'A', 'Landman identified executive, legislative, electoral systems and party systems as key institutional areas.'),
    (v_course_id, 'In comparative Politics, ____ design is used to compare political systems that share a host of common features in an effort to neutralize some differences while highlighting others', 'multiple_choice', 'Most Different System', 'Most Similar System', 'Single Case', 'Cross-sectional', 'B', 'Most Similar System design controls for many variables by comparing similar cases.'),
    (v_course_id, 'The J.S. Mill''s (1843) method of difference seeks to identify the key features that are different among similar countries and which explains the observed _______', 'multiple_choice', 'Cultural similarities', 'Political outcome', 'Economic development', 'Social structures', 'B', 'Method of difference identifies varying factors that explain different political outcomes.'),
    (v_course_id, 'One of the most important strategies for selecting a topic, and considered to be more than a technique for conducting research is the ___________', 'multiple_choice', 'Statistical analysis', 'Case study method', 'Survey research', 'Content analysis', 'B', 'Case study method is both a topic selection strategy and research technique.'),
    (v_course_id, 'The consensus system is more often referred to as ____________', 'multiple_choice', 'British Model', 'American Model', 'West German Model', 'French Model', 'C', 'Consensus democracy is often associated with the West German model.'),
    (v_course_id, 'The method that is particularly well suited for scholars engaged in area Studies are called ____________', 'multiple_choice', 'Statistical analysis', 'Most similar systems design', 'Experimental design', 'Survey research', 'B', 'Most similar systems design is commonly used in area studies research.'),
    (v_course_id, 'The Single –country studies are also useful for generating hypotheses for ____ that are yet to be fully specified', 'multiple_choice', 'Policies', 'Theories', 'Laws', 'Methods', 'B', 'Single-country studies can generate hypotheses for theoretical development.'),
    (v_course_id, 'A decisive scientific principle that is often violated by comparative politics is the ____', 'multiple_choice', 'principle of selection', 'principle of objectivity', 'principle of verification', 'principle of falsification', 'A', 'Case selection bias is a common methodological challenge in comparative politics.'),
    (v_course_id, 'The method of governmental organization in which authority is divided between the central government and the constituent units is called ____', 'multiple_choice', 'Unitarism', 'Federalism', 'Confederalism', 'Regionalism', 'B', 'Federalism divides authority between central and regional governments.'),
    (v_course_id, 'The process of how a country''s administration is organized and how its functions, is regarded as ____', 'multiple_choice', 'Political Theory', 'Public Administration', 'International Relations', 'Political Economy', 'B', 'Public administration studies governmental organization and functioning.'),
    (v_course_id, 'The practice of Federalism emerged among nations as a result of a perceived need for ____, as well as the protection of the rights of its component units', 'multiple_choice', 'Weaker political units', 'Stronger political unit', 'Economic independence', 'Cultural autonomy', 'B', 'Federalism often emerges from needs for both unity and regional autonomy.'),
    (v_course_id, 'The semi presidential system has its roots in the fifth Republic of ____', 'multiple_choice', 'United States', 'France', 'Germany', 'Britain', 'B', 'Semi-presidentialism was established in France''s Fifth Republic.'),
    (v_course_id, 'The National Assembly in France is directly elected by ____', 'multiple_choice', 'Adult Suffrage', 'The President', 'The Senate', 'Regional councils', 'A', 'The French National Assembly is directly elected through universal adult suffrage.'),
    (v_course_id, 'The abstract concepts which are specified at a high level of abstraction and are chosen purposely to give an explanation to the phenomenon of a researcher''s interest is called ______________', 'multiple_choice', 'Variables', 'Constructs', 'Hypotheses', 'Theories', 'B', 'Constructs are abstract concepts used to explain phenomena of interest.'),
    (v_course_id, 'The model or system of government in which the executive is elected by the people into a fixed term of office is referred to as ____', 'multiple_choice', 'Parliamentary system', 'Semi Presidential system', 'Presidential system', 'Monarchical system', 'C', 'Presidential systems feature directly elected executives with fixed terms.'),
    (v_course_id, 'Comparative Analysis of a particular political phenomenon cannot be said to be carried out successfully, without an extensive ___', 'multiple_choice', 'Theoretical argument', 'Historical background', 'Statistical data', 'Case selection', 'A', 'Strong theoretical foundations are essential for meaningful comparative analysis.'),
    (v_course_id, 'The approaches to the study of politics includes; normative philosophical, descriptive institutional, ____ and scientific behavioural', 'multiple_choice', 'Historical comparative', 'Eclectic/ post behavioural', 'Rational choice', 'Marxist', 'B', 'Eclectic/post-behavioral approaches combine various methodological perspectives.'),
    (v_course_id, 'According to Sartori (1991) we compare in order to ____ the observed units of variation', 'multiple_choice', 'Ignore', 'Control', 'Eliminate', 'Complicate', 'B', 'Sartori argued comparison helps control for variation across cases.'),
    (v_course_id, 'In comparative analysis, the more open the relationship between the research question and ____ , the more positive the expected analytical results will be', 'multiple_choice', 'Research design', 'Theoretical framework', 'Methodology', 'Case selection', 'A', 'Alignment between research questions and design is crucial for successful analysis.'),
    (v_course_id, 'Arend Lijphart (1971) stresses that there are three types of spatial analysis, and this includes; the statistically based; __________ and the comparable case approach', 'multiple_choice', 'Experimental', 'Case-Oriented', 'Historical', 'Theoretical', 'B', 'Lijphart identified statistical, case-oriented, and comparable case approaches.'),
    (v_course_id, 'The Variables that make up the environment of the core subject in comparative analysis is called ______________', 'multiple_choice', 'Independent Variables', 'Dependent Variables', 'Contextual Variables', 'Control Variables', 'C', 'Contextual variables represent the environmental factors surrounding the core subject.'),
    (v_course_id, 'Cases are considered as the units of observation that are defined by time and place and systematically linked to the ____ in context', 'multiple_choice', 'Research Question', 'Theoretical Framework', 'Methodology', 'Hypothesis', 'A', 'Cases are fundamentally linked to the research question being investigated.');

    -- Fill in the blank questions (15% - 15 questions)
    INSERT INTO questions (course_id, question_text, question_type, correct_answer, explanation) VALUES
    (v_course_id, 'The definition of politics as "who gets what, when and how" was made by __', 'fill_in_blank', 'Harold Laswell', 'Harold Lasswell famously defined politics as the distribution of resources and power.'),
    (v_course_id, 'To Aristotle, politics was the search for the __', 'fill_in_blank', 'good life', 'Aristotle viewed politics as the means to achieve the good life for citizens.'),
    (v_course_id, 'According to Stephen Giliat there are__ major traditions in the understanding of Politics', 'fill_in_blank', 'Two', 'Giliat identified two main traditions in political understanding.'),
    (v_course_id, 'The formulation of a body of general rules and logically consistent and universally valid statement about the universe is the ultimate goal of __', 'fill_in_blank', 'Science', 'Science aims to develop systematic, universally valid knowledge.'),
    (v_course_id, '___ has been described as an "adventure of the human spirit"?', 'fill_in_blank', 'Science', 'Science is often characterized as a creative human endeavor.'),
    (v_course_id, 'The ___entails vigorous procedures starting from the selection of problem to be solved or analysed, followed by formulation of hypothesis, gathering of data and testing of hypothesis and finally, the use of findings to refuse, modify or support existing theories?', 'fill_in_blank', 'scientific method', 'The scientific method involves systematic procedures from problem selection to theory testing.'),
    (v_course_id, 'The theory of evolution and the theory of gravity in the natural science are based on the systematic collection of ___?', 'fill_in_blank', 'evidence', 'Scientific theories are built on systematic evidence collection.'),
    (v_course_id, 'The first difference between natural science and political science is the __?', 'fill_in_blank', 'Role of experimentation', 'Experimental control is more challenging in political science than natural sciences.'),
    (v_course_id, 'Experimentation and repeated empirical verification give theories in the natural science, the status of __?', 'fill_in_blank', 'Laws', 'Repeated verification allows natural science theories to become scientific laws.'),
    (v_course_id, '"___ law" state that electoral systems based on single member districts tend to produce two parties?', 'fill_in_blank', 'Duverger''s', 'Duverger''s law describes the relationship between electoral systems and party systems.'),
    (v_course_id, 'If scientific knowledge is to be verifiable, science must be __?', 'fill_in_blank', 'Empirical', 'Empirical verification is essential for scientific knowledge.'),
    (v_course_id, '__ is said to be systematic when it is organised into an intelligible pattern or structure with significant relationships made clear?', 'fill_in_blank', 'Knowledge', 'Systematic knowledge involves organized patterns and clear relationships.'),
    (v_course_id, 'Traditionally, the study of politics was dominated by ___ reflections on universal political values?', 'fill_in_blank', 'Philosophical', 'Traditional political study emphasized philosophical reflection on values.'),
    (v_course_id, 'The____ approach to political inquiry focuses on the formal structures and agencies of government?', 'fill_in_blank', 'Institutional', 'Institutional approach studies formal governmental structures and organizations.'),
    (v_course_id, 'The key assumption of the behavioural approach or behaviouralism centers on___ in political behavior?', 'fill_in_blank', 'Uniformities', 'Behavioralism assumes discoverable regularities in political behavior.');

    -- Additional multiple choice questions to reach 85 total
    INSERT INTO questions (course_id, question_text, question_type, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
    (v_course_id, 'The key assumption of the behavioural approach or behaviouralism centers on___ in political behavior?', 'multiple_choice', 'Randomness', 'Uniformities', 'Complexity', 'Unpredictability', 'B', 'Behavioralism seeks to discover patterns and regularities in political behavior.'),
    (v_course_id, 'As an approach to the study of politics, behavioural approach introduces __ major elements to political science?', 'multiple_choice', 'One', 'Two', 'Three', 'Four', 'B', 'Behavioralism introduced scientific methodology and individual-level analysis.'),
    (v_course_id, 'The second element that behaviouralism brought to the study of politics was the emphasis in the use of ___ in political analysis?', 'multiple_choice', 'historical records', 'scientific methods', 'philosophical reasoning', 'case studies', 'B', 'Behavioralism emphasized rigorous scientific methods in political analysis.'),
    (v_course_id, 'According to ___ comparative Politics is simply an examination of political realities in countries all over the world, looking at the many ways people behave in politics.', 'multiple_choice', 'David Easton', 'Michael Sodaro', 'Gabriel Almond', 'Arend Lijphart', 'B', 'Michael Sodaro provided this broad definition of comparative politics.'),
    (v_course_id, 'Comparative politics is characterized by an empirical approach based on the __?', 'multiple_choice', 'historical method', 'comparative method', 'statistical method', 'case study method', 'B', 'The comparative method is the defining characteristic of comparative politics.'),
    (v_course_id, 'According to _______________comparative politics does not have a substantive focus in itself, but rather a methodological one', 'multiple_choice', 'David Easton', 'Arend Lijphart', 'Gabriel Almond', 'Karl Deutsch', 'B', 'Lijphart emphasized comparative politics as a methodological approach.'),
    (v_course_id, 'The earliest adopted method of comparing political institutions was __?', 'multiple_choice', 'Comparative Government', 'Comparative Politics', 'Political Theory', 'International Relations', 'A', 'Comparative government was the initial approach before comparative politics.'),
    (v_course_id, 'Philosophers who studied government on comparative basis used the __ approach?', 'multiple_choice', 'Scientific', 'Descriptive', 'Statistical', 'Experimental', 'B', 'Early comparative studies used descriptive rather than scientific approaches.'),
    (v_course_id, 'The __ method is discountenanced under the comparative governments', 'multiple_choice', 'Historical', 'Scientific', 'Philosophical', 'Legal', 'B', 'Traditional comparative government avoided scientific methods.'),
    (v_course_id, '____________ is that area of study in political science which adopts the scientific method thereby going beyond the study of the structure and institutions of government through traditional descriptive approach', 'multiple_choice', 'Political Theory', 'Comparative Politics', 'International Relations', 'Public Administration', 'B', 'Comparative politics uses scientific methods beyond traditional institutional description.'),
    (v_course_id, '__ is that area of study in political science which adopts the scientific method thereby going beyond the study of the structure and institutions of government through traditional descriptive approach', 'multiple_choice', 'Political Philosophy', 'Comparative Politics', 'Political Economy', 'Public Policy', 'B', 'Comparative politics represents the scientific study of political systems.'),
    (v_course_id, 'Barrington Moore compared___ in countries like England, Russia and Japan', 'multiple_choice', 'Elections', 'Revolutions', 'Political parties', 'Bureaucracies', 'B', 'Barrington Moore''s classic work compared social origins of dictatorship and democracy.'),
    (v_course_id, 'The second Phase in the Development of Comparative Politics is the ___________', 'multiple_choice', 'Ancient period', 'Renaissance period', 'Modern period', 'Post-modern period', 'B', 'The Renaissance marked the second major phase in comparative politics development.'),
    (v_course_id, 'The term "Political Science" was first used by __________', 'multiple_choice', 'Aristotle', 'Jean Bodin', 'Thomas Hobbes', 'John Locke', 'B', 'Jean Bodin first used the term "political science" in the 16th century.'),
    (v_course_id, 'The third Phase in the Development of Comparative Politics is the __________', 'multiple_choice', 'age of enlightenment', 'middle ages', 'modern era', 'contemporary period', 'A', 'The Enlightenment represented the third developmental phase.');

    -- Additional fill in the blank questions to complete the set
    INSERT INTO questions (course_id, question_text, question_type, correct_answer, explanation) VALUES
    (v_course_id, 'The Russian revolution of 1917 pioneered by ________', 'fill_in_blank', 'Joseph Lenin', 'Lenin led the Bolshevik revolution that established Soviet communism.'),
    (v_course_id, 'One of the major characteristics of the traditional approach is that it adopts the __ method', 'fill_in_blank', 'Historical', 'Traditional approaches often used historical and philosophical methods.'),
    (v_course_id, 'There are five types of adaptation: Conformity, innovation, ritualism, retreatism and ________rebellion.', 'fill_in_blank', 'Rebellion', 'Merton''s typology includes rebellion as a mode of individual adaptation.'),
    (v_course_id, 'Precision is the recording of data and the statement of findings Requires ___ and ___?', 'fill_in_blank', 'measurement and quantification', 'Scientific precision demands systematic measurement and quantification.'),
    (v_course_id, 'Ethical evaluation and empirical explanation involve __ different Proportions?', 'fill_in_blank', 'Two', 'Normative and empirical approaches involve different methodological proportions.');

DO $$
DECLARE
    v_course_id UUID;
BEGIN
    SELECT id INTO v_course_id FROM courses WHERE code = 'POL228' LIMIT 1;

    -- Multiple choice questions (85% - 85 questions)
    INSERT INTO questions (course_id, question_text, question_type, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
    (v_course_id, 'In comparative analysis, ____ is used to interrogate whether or not the measurements used in a given research are properly operationalized', 'multiple_choice', 'External validity', 'Internal validity', 'Reliability', 'Objectivity', 'B', 'Internal validity assesses whether measurements properly capture the intended concepts.'),
    (v_course_id, 'As an approach to the study of politics, the scientific approach introduced two major elements; and this are, emphasis on ____, and on the individual as the central unit of political analysis', 'multiple_choice', 'Scientific method', 'Historical analysis', 'Philosophical reasoning', 'Case studies', 'A', 'The scientific approach emphasizes systematic methodology and individual-level analysis.'),
    (v_course_id, 'David Easton insists that post behavioralism should be backed by ____ and ____', 'multiple_choice', 'Action and Relevance', 'Theory and Practice', 'Data and Analysis', 'Politics and Science', 'A', 'Easton argued post-behavioralism should focus on action and relevance to real-world problems.'),
    (v_course_id, 'Comparative politics relies on the method of ___, and method of "agreement"', 'multiple_choice', 'Difference', 'Similarity', 'Correlation', 'Causation', 'A', 'J.S. Mill''s methods of difference and agreement are fundamental to comparative analysis.'),
    (v_course_id, 'The two main comparative approaches for choosing cases are: ____, and most different systems (MDS)', 'multiple_choice', 'Most Similar System (MSS)', 'Single Case Study', 'Cross-national Analysis', 'Historical Comparison', 'A', 'Most Similar Systems design compares cases that share many characteristics.'),
    (v_course_id, 'The discipline of comparative politics has undergone three key changes, and this includes; ____, object of inquiry, method of deploying data', 'multiple_choice', 'Theoretical frameworks', 'Empirical findings', 'Research methods', 'Political ideologies', 'B', 'Comparative politics has evolved in its empirical findings, objects of study, and data methods.'),
    (v_course_id, 'The simultaneous study of a large number of nation-states in comparative studies is referred to as --------------', 'multiple_choice', 'Case study method', 'The cross-national approach', 'Historical analysis', 'Qualitative research', 'B', 'Cross-national approach involves comparing multiple countries simultaneously.'),
    (v_course_id, 'One of the goals of the exploratory research method is to prove that ____', 'multiple_choice', 'Hypotheses are true', 'Further investigation is necessary', 'Theories are complete', 'Methods are perfect', 'B', 'Exploratory research often identifies areas needing further study.'),
    (v_course_id, 'A key feature of the Quantitative research method, is that data gathered are analyzed ______', 'multiple_choice', 'Qualitatively', 'Narratively', 'Numerically', 'Historically', 'C', 'Quantitative research uses numerical data and statistical analysis.'),
    (v_course_id, 'In the field of comparative politics, the term politics have three meanings, and this includes; politics as a political activity, ____, and a political process', 'multiple_choice', 'Political power', 'Political theory', 'Political science', 'Political history', 'A', 'Politics can be understood as activity, power, and process.'),
    (v_course_id, 'Systems theory is of great relevance in political Analysis because it does not only, ____, but also encourages the evaluation of the various patterns and levels of relationship amongst different units', 'multiple_choice', 'Ignore external factors', 'Identify the component units in a system', 'Focus only on outputs', 'Eliminate variables', 'B', 'Systems theory identifies components and their interrelationships within political systems.'),
    (v_course_id, 'The three primary components of every political system include the ____ ; the regime; and the authorities', 'multiple_choice', 'Political community', 'Economic system', 'Social structure', 'Cultural norms', 'A', 'Easton identified political community, regime, and authorities as system components.'),
    (v_course_id, 'The Input – Output model of David Easton explains the behaviour of ____ as well as the environment in a particular system', 'multiple_choice', 'Political System', 'Economic System', 'Social System', 'Cultural System', 'A', 'Easton''s model analyzes how political systems process inputs into outputs.'),
    (v_course_id, 'In Duverger''s law, an electoral system based on ____, tend to produce two parties', 'multiple_choice', 'Proportional representation', 'Single member district', 'Mixed system', 'Party list', 'B', 'Duverger''s law states single-member districts tend toward two-party systems.'),
    (v_course_id, 'In its developmental phases, the ____ period marked the rebirth of comparative politics', 'multiple_choice', 'Ancient', 'Medieval', 'Renaissance', 'Modern', 'C', 'The Renaissance period revived comparative political studies after the Middle Ages.'),
    (v_course_id, 'The system theory resonated as a result of the movement to unite ____, and scientific analysis', 'multiple_choice', 'Philosophy', 'Science', 'History', 'Economics', 'B', 'Systems theory integrated scientific analysis with political study.'),
    (v_course_id, 'Considered as one of the sub disciplines of Political Science, the goal of comparative politics is to understand, and ____ the nature of political power and interactions among nations', 'multiple_choice', 'Ignore', 'Explain', 'Complicate', 'Simplify', 'B', 'Comparative politics aims to understand and explain political power dynamics.'),
    (v_course_id, 'Though it originated among the Anthropologists and Sociologists, ____ adopted the concept of structural functionalism in political Analysis', 'multiple_choice', 'Karl Marx', 'Gabriel Almond', 'David Easton', 'Max Weber', 'B', 'Gabriel Almond adapted structural-functionalism for political science.'),
    (v_course_id, 'More often referred to as the "master strategy", the comparative approach is used in ____ about a specific case study', 'multiple_choice', 'Ignoring context', 'Drawing inferences', 'Eliminating variables', 'Simplifying complexity', 'B', 'Comparative method helps draw broader inferences from specific cases.'),
    (v_course_id, 'In political inquiry, ____ rely on the use of observation and measurement', 'multiple_choice', 'Normative approach', 'Empirical approach', 'Philosophical approach', 'Historical approach', 'B', 'Empirical approaches emphasize observation and measurement.'),
    (v_course_id, 'The output function in a system theory is performed by ____, according to Gabriel Almond', 'multiple_choice', 'Legislature', 'Executive', 'Judiciary', 'Political parties', 'B', 'Almond identified the executive as performing output functions in political systems.'),
    (v_course_id, 'The ____ theory help political scientists to understand how democracy is supposed to work in principle, and how they work in practice', 'multiple_choice', 'Authoritarian', 'Democratic', 'Socialist', 'Communist', 'B', 'Democratic theory examines both ideal and actual democratic functioning.'),
    (v_course_id, 'The ____ focuses on philosophy, values and norms in carrying out political Analysis', 'multiple_choice', 'Empirical Approach', 'Normative Approach', 'Scientific Approach', 'Behavioral Approach', 'B', 'Normative approach emphasizes values, ethics, and philosophical principles.'),
    (v_course_id, 'Logic as a concept dates back to the writings of ____, who established it in philosophy', 'multiple_choice', 'Plato', 'Aristotle', 'Socrates', 'Descartes', 'B', 'Aristotle is considered the founder of formal logic.'),
    (v_course_id, 'The error of explaining something in terms of one sole cause when other causes could also be at work is referred to as ________', 'multiple_choice', 'Reductivism', 'Holism', 'Pluralism', 'Complexity', 'A', 'Reductivism oversimplifies by attributing outcomes to single causes.'),
    (v_course_id, 'The formal systematic study of the principles of valid inference and correct reasoning is called _____________', 'multiple_choice', 'Epistemology', 'Logic', 'Methodology', 'Ontology', 'B', 'Logic is the study of valid reasoning and inference.'),
    (v_course_id, 'In the Aristotle classification of regimes, the good types include monarchy, aristocracy, and ____', 'multiple_choice', 'Tyranny', 'Polity', 'Oligarchy', 'Democracy', 'B', 'Aristotle classified polity as a good form of government by the many.'),
    (v_course_id, 'According to Arend Lijphart, the discussion of the comparative method is not complete without giving a consideration to the _________', 'multiple_choice', 'Statistical Analysis', 'Case Study Method', 'Historical Method', 'Experimental Method', 'B', 'Lijphart emphasized the importance of case study methods in comparative politics.'),
    (v_course_id, 'According to Landman (2008), the comparative study of institutional designs involves three types of institutions, and this includes; executive, legislative arrangements, ____, as well as the political party system', 'multiple_choice', 'The electoral system', 'The judicial system', 'The bureaucracy', 'The military', 'A', 'Landman identified executive, legislative, electoral systems and party systems as key institutional areas.'),
    (v_course_id, 'In comparative Politics, ____ design is used to compare political systems that share a host of common features in an effort to neutralize some differences while highlighting others', 'multiple_choice', 'Most Different System', 'Most Similar System', 'Single Case', 'Cross-sectional', 'B', 'Most Similar System design controls for many variables by comparing similar cases.'),
    (v_course_id, 'The J.S. Mill''s (1843) method of difference seeks to identify the key features that are different among similar countries and which explains the observed _______', 'multiple_choice', 'Cultural similarities', 'Political outcome', 'Economic development', 'Social structures', 'B', 'Method of difference identifies varying factors that explain different political outcomes.'),
    (v_course_id, 'One of the most important strategies for selecting a topic, and considered to be more than a technique for conducting research is the ___________', 'multiple_choice', 'Statistical analysis', 'Case study method', 'Survey research', 'Content analysis', 'B', 'Case study method is both a topic selection strategy and research technique.'),
    (v_course_id, 'The consensus system is more often referred to as ____________', 'multiple_choice', 'British Model', 'American Model', 'West German Model', 'French Model', 'C', 'Consensus democracy is often associated with the West German model.'),
    (v_course_id, 'The method that is particularly well suited for scholars engaged in area Studies are called ____________', 'multiple_choice', 'Statistical analysis', 'Most similar systems design', 'Experimental design', 'Survey research', 'B', 'Most similar systems design is commonly used in area studies research.'),
    (v_course_id, 'The Single –country studies are also useful for generating hypotheses for ____ that are yet to be fully specified', 'multiple_choice', 'Policies', 'Theories', 'Laws', 'Methods', 'B', 'Single-country studies can generate hypotheses for theoretical development.'),
    (v_course_id, 'A decisive scientific principle that is often violated by comparative politics is the ____', 'multiple_choice', 'principle of selection', 'principle of objectivity', 'principle of verification', 'principle of falsification', 'A', 'Case selection bias is a common methodological challenge in comparative politics.'),
    (v_course_id, 'The method of governmental organization in which authority is divided between the central government and the constituent units is called ____', 'multiple_choice', 'Unitarism', 'Federalism', 'Confederalism', 'Regionalism', 'B', 'Federalism divides authority between central and regional governments.'),
    (v_course_id, 'The process of how a country''s administration is organized and how its functions, is regarded as ____', 'multiple_choice', 'Political Theory', 'Public Administration', 'International Relations', 'Political Economy', 'B', 'Public administration studies governmental organization and functioning.'),
    (v_course_id, 'The practice of Federalism emerged among nations as a result of a perceived need for ____, as well as the protection of the rights of its component units', 'multiple_choice', 'Weaker political units', 'Stronger political unit', 'Economic independence', 'Cultural autonomy', 'B', 'Federalism often emerges from needs for both unity and regional autonomy.'),
    (v_course_id, 'The semi presidential system has its roots in the fifth Republic of ____', 'multiple_choice', 'United States', 'France', 'Germany', 'Britain', 'B', 'Semi-presidentialism was established in France''s Fifth Republic.'),
    (v_course_id, 'The National Assembly in France is directly elected by ____', 'multiple_choice', 'Adult Suffrage', 'The President', 'The Senate', 'Regional councils', 'A', 'The French National Assembly is directly elected through universal adult suffrage.'),
    (v_course_id, 'The abstract concepts which are specified at a high level of abstraction and are chosen purposely to give an explanation to the phenomenon of a researcher''s interest is called ______________', 'multiple_choice', 'Variables', 'Constructs', 'Hypotheses', 'Theories', 'B', 'Constructs are abstract concepts used to explain phenomena of interest.'),
    (v_course_id, 'The model or system of government in which the executive is elected by the people into a fixed term of office is referred to as ____', 'multiple_choice', 'Parliamentary system', 'Semi Presidential system', 'Presidential system', 'Monarchical system', 'C', 'Presidential systems feature directly elected executives with fixed terms.'),
    (v_course_id, 'Comparative Analysis of a particular political phenomenon cannot be said to be carried out successfully, without an extensive ___', 'multiple_choice', 'Theoretical argument', 'Historical background', 'Statistical data', 'Case selection', 'A', 'Strong theoretical foundations are essential for meaningful comparative analysis.'),
    (v_course_id, 'The approaches to the study of politics includes; normative philosophical, descriptive institutional, ____ and scientific behavioural', 'multiple_choice', 'Historical comparative', 'Eclectic/ post behavioural', 'Rational choice', 'Marxist', 'B', 'Eclectic/post-behavioral approaches combine various methodological perspectives.'),
    (v_course_id, 'According to Sartori (1991) we compare in order to ____ the observed units of variation', 'multiple_choice', 'Ignore', 'Control', 'Eliminate', 'Complicate', 'B', 'Sartori argued comparison helps control for variation across cases.'),
    (v_course_id, 'In comparative analysis, the more open the relationship between the research question and ____ , the more positive the expected analytical results will be', 'multiple_choice', 'Research design', 'Theoretical framework', 'Methodology', 'Case selection', 'A', 'Alignment between research questions and design is crucial for successful analysis.'),
    (v_course_id, 'Arend Lijphart (1971) stresses that there are three types of spatial analysis, and this includes; the statistically based; __________ and the comparable case approach', 'multiple_choice', 'Experimental', 'Case-Oriented', 'Historical', 'Theoretical', 'B', 'Lijphart identified statistical, case-oriented, and comparable case approaches.'),
    (v_course_id, 'The Variables that make up the environment of the core subject in comparative analysis is called ______________', 'multiple_choice', 'Independent Variables', 'Dependent Variables', 'Contextual Variables', 'Control Variables', 'C', 'Contextual variables represent the environmental factors surrounding the core subject.'),
    (v_course_id, 'Cases are considered as the units of observation that are defined by time and place and systematically linked to the ____ in context', 'multiple_choice', 'Research Question', 'Theoretical Framework', 'Methodology', 'Hypothesis', 'A', 'Cases are fundamentally linked to the research question being investigated.');

    -- Fill in the blank questions (15% - 15 questions)
    INSERT INTO questions (course_id, question_text, question_type, correct_answer, explanation) VALUES
    (v_course_id, 'The definition of politics as "who gets what, when and how" was made by __', 'fill_in_blank', 'Harold Laswell', 'Harold Lasswell famously defined politics as the distribution of resources and power.'),
    (v_course_id, 'To Aristotle, politics was the search for the __', 'fill_in_blank', 'good life', 'Aristotle viewed politics as the means to achieve the good life for citizens.'),
    (v_course_id, 'According to Stephen Giliat there are__ major traditions in the understanding of Politics', 'fill_in_blank', 'Two', 'Giliat identified two main traditions in political understanding.'),
    (v_course_id, 'The formulation of a body of general rules and logically consistent and universally valid statement about the universe is the ultimate goal of __', 'fill_in_blank', 'Science', 'Science aims to develop systematic, universally valid knowledge.'),
    (v_course_id, '___ has been described as an "adventure of the human spirit"?', 'fill_in_blank', 'Science', 'Science is often characterized as a creative human endeavor.'),
    (v_course_id, 'The ___entails vigorous procedures starting from the selection of problem to be solved or analysed, followed by formulation of hypothesis, gathering of data and testing of hypothesis and finally, the use of findings to refuse, modify or support existing theories?', 'fill_in_blank', 'scientific method', 'The scientific method involves systematic procedures from problem selection to theory testing.'),
    (v_course_id, 'The theory of evolution and the theory of gravity in the natural science are based on the systematic collection of ___?', 'fill_in_blank', 'evidence', 'Scientific theories are built on systematic evidence collection.'),
    (v_course_id, 'The first difference between natural science and political science is the __?', 'fill_in_blank', 'Role of experimentation', 'Experimental control is more challenging in political science than natural sciences.'),
    (v_course_id, 'Experimentation and repeated empirical verification give theories in the natural science, the status of __?', 'fill_in_blank', 'Laws', 'Repeated verification allows natural science theories to become scientific laws.'),
    (v_course_id, '"___ law" state that electoral systems based on single member districts tend to produce two parties?', 'fill_in_blank', 'Duverger''s', 'Duverger''s law describes the relationship between electoral systems and party systems.'),
    (v_course_id, 'If scientific knowledge is to be verifiable, science must be __?', 'fill_in_blank', 'Empirical', 'Empirical verification is essential for scientific knowledge.'),
    (v_course_id, '__ is said to be systematic when it is organised into an intelligible pattern or structure with significant relationships made clear?', 'fill_in_blank', 'Knowledge', 'Systematic knowledge involves organized patterns and clear relationships.'),
    (v_course_id, 'Traditionally, the study of politics was dominated by ___ reflections on universal political values?', 'fill_in_blank', 'Philosophical', 'Traditional political study emphasized philosophical reflection on values.'),
    (v_course_id, 'The____ approach to political inquiry focuses on the formal structures and agencies of government?', 'fill_in_blank', 'Institutional', 'Institutional approach studies formal governmental structures and organizations.'),
    (v_course_id, 'The key assumption of the behavioural approach or behaviouralism centers on___ in political behavior?', 'fill_in_blank', 'Uniformities', 'Behavioralism assumes discoverable regularities in political behavior.');

    -- Additional multiple choice questions to reach 85 total
    INSERT INTO questions (course_id, question_text, question_type, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
    (v_course_id, 'The key assumption of the behavioural approach or behaviouralism centers on___ in political behavior?', 'multiple_choice', 'Randomness', 'Uniformities', 'Complexity', 'Unpredictability', 'B', 'Behavioralism seeks to discover patterns and regularities in political behavior.'),
    (v_course_id, 'As an approach to the study of politics, behavioural approach introduces __ major elements to political science?', 'multiple_choice', 'One', 'Two', 'Three', 'Four', 'B', 'Behavioralism introduced scientific methodology and individual-level analysis.'),
    (v_course_id, 'The second element that behaviouralism brought to the study of politics was the emphasis in the use of ___ in political analysis?', 'multiple_choice', 'historical records', 'scientific methods', 'philosophical reasoning', 'case studies', 'B', 'Behavioralism emphasized rigorous scientific methods in political analysis.'),
    (v_course_id, 'According to ___ comparative Politics is simply an examination of political realities in countries all over the world, looking at the many ways people behave in politics.', 'multiple_choice', 'David Easton', 'Michael Sodaro', 'Gabriel Almond', 'Arend Lijphart', 'B', 'Michael Sodaro provided this broad definition of comparative politics.'),
    (v_course_id, 'Comparative politics is characterized by an empirical approach based on the __?', 'multiple_choice', 'historical method', 'comparative method', 'statistical method', 'case study method', 'B', 'The comparative method is the defining characteristic of comparative politics.'),
    (v_course_id, 'According to _______________comparative politics does not have a substantive focus in itself, but rather a methodological one', 'multiple_choice', 'David Easton', 'Arend Lijphart', 'Gabriel Almond', 'Karl Deutsch', 'B', 'Lijphart emphasized comparative politics as a methodological approach.'),
    (v_course_id, 'The earliest adopted method of comparing political institutions was __?', 'multiple_choice', 'Comparative Government', 'Comparative Politics', 'Political Theory', 'International Relations', 'A', 'Comparative government was the initial approach before comparative politics.'),
    (v_course_id, 'Philosophers who studied government on comparative basis used the __ approach?', 'multiple_choice', 'Scientific', 'Descriptive', 'Statistical', 'Experimental', 'B', 'Early comparative studies used descriptive rather than scientific approaches.'),
    (v_course_id, 'The __ method is discountenanced under the comparative governments', 'multiple_choice', 'Historical', 'Scientific', 'Philosophical', 'Legal', 'B', 'Traditional comparative government avoided scientific methods.'),
    (v_course_id, '____________ is that area of study in political science which adopts the scientific method thereby going beyond the study of the structure and institutions of government through traditional descriptive approach', 'multiple_choice', 'Political Theory', 'Comparative Politics', 'International Relations', 'Public Administration', 'B', 'Comparative politics uses scientific methods beyond traditional institutional description.'),
    (v_course_id, '__ is that area of study in political science which adopts the scientific method thereby going beyond the study of the structure and institutions of government through traditional descriptive approach', 'multiple_choice', 'Political Philosophy', 'Comparative Politics', 'Political Economy', 'Public Policy', 'B', 'Comparative politics represents the scientific study of political systems.'),
    (v_course_id, 'Barrington Moore compared___ in countries like England, Russia and Japan', 'multiple_choice', 'Elections', 'Revolutions', 'Political parties', 'Bureaucracies', 'B', 'Barrington Moore''s classic work compared social origins of dictatorship and democracy.'),
    (v_course_id, 'The second Phase in the Development of Comparative Politics is the ___________', 'multiple_choice', 'Ancient period', 'Renaissance period', 'Modern period', 'Post-modern period', 'B', 'The Renaissance marked the second major phase in comparative politics development.'),
    (v_course_id, 'The term "Political Science" was first used by __________', 'multiple_choice', 'Aristotle', 'Jean Bodin', 'Thomas Hobbes', 'John Locke', 'B', 'Jean Bodin first used the term "political science" in the 16th century.'),
    (v_course_id, 'The third Phase in the Development of Comparative Politics is the __________', 'multiple_choice', 'age of enlightenment', 'middle ages', 'modern era', 'contemporary period', 'A', 'The Enlightenment represented the third developmental phase.');

    -- Additional fill in the blank questions to complete the set
    INSERT INTO questions (course_id, question_text, question_type, correct_answer, explanation) VALUES
    (v_course_id, 'The Russian revolution of 1917 pioneered by ________', 'fill_in_blank', 'Joseph Lenin', 'Lenin led the Bolshevik revolution that established Soviet communism.'),
    (v_course_id, 'One of the major characteristics of the traditional approach is that it adopts the __ method', 'fill_in_blank', 'Historical', 'Traditional approaches often used historical and philosophical methods.'),
    (v_course_id, 'There are five types of adaptation: Conformity, innovation, ritualism, retreatism and ________rebellion.', 'fill_in_blank', 'Rebellion', 'Merton''s typology includes rebellion as a mode of individual adaptation.'),
    (v_course_id, 'Precision is the recording of data and the statement of findings Requires ___ and ___?', 'fill_in_blank', 'measurement and quantification', 'Scientific precision demands systematic measurement and quantification.'),
    (v_course_id, 'Ethical evaluation and empirical explanation involve __ different Proportions?', 'fill_in_blank', 'Two', 'Normative and empirical approaches involve different methodological proportions.');

END $$;