DO $$
DECLARE
    v_course_id UUID;
BEGIN
    SELECT id INTO v_course_id FROM courses WHERE code = 'POL226' LIMIT 1;

    -- Fill in the blank questions (15% - 15 questions)
    INSERT INTO questions (course_id, question_text, question_type, correct_answer, explanation) VALUES
    (v_course_id, 'A system in which the appointment and conditions of service of an employee are determined solely at the employees own intrinsic qualifications and personal capacities and physical fitness is called the ______', 'fill_in_blank', 'Merit system', 'The merit system bases employment on qualifications and abilities rather than political connections.'),
    (v_course_id, 'A system whereby the public office constitutes a spoil to be enjoyed by the victorious political party at the polls is known as _________', 'fill_in_blank', 'Spoils system', 'The spoils system rewards political supporters with government positions.'),
    (v_course_id, '________ Act gave the civil service permanency of tenure and its present character', 'fill_in_blank', 'Pendleton', 'The Pendleton Act of 1883 established the merit-based civil service system in the US.'),
    (v_course_id, 'The establishment of a two-way flow of mutual understanding and information between an organisation and its public has been the fundamental objective of ______', 'fill_in_blank', 'Public relations', 'Public relations focuses on building mutual understanding between organizations and their publics.'),
    (v_course_id, 'The organisations which bring members of the same profession together for the exchange of information and experience and for the advancement of their profession is known as ________', 'fill_in_blank', 'Professional Association', 'Professional associations advance specific professions through networking and standards.'),
    (v_course_id, 'The averred objective to seek an improvement on the wages and other conditions of service of their member is the responsibility of ___________', 'fill_in_blank', 'Trade unions', 'Trade unions primarily focus on improving wages and working conditions for members.'),
    (v_course_id, 'An employee that is equipped with in-depth knowledge of science and technology in one particular branch or sector is known as __________', 'fill_in_blank', 'A specialist', 'Specialists possess deep expertise in specific technical or professional areas.'),
    (v_course_id, 'The employees who are non-specialists or technocrats in an organisation are called ________', 'fill_in_blank', 'Bureaucrats', 'Bureaucrats are general administrators rather than technical specialists.'),
    (v_course_id, 'The specialists are commonly termed as _________', 'fill_in_blank', 'Technocrats', 'Technocrats are technical experts who hold administrative positions.'),
    (v_course_id, 'A career person within the executive branch who by the breath of his experience is competent to deal effectively with complex problems of relationship among agencies or officials is known as _________', 'fill_in_blank', 'A generalist', 'Generalists have broad experience across multiple administrative areas.'),
    (v_course_id, 'In an organisation, the grading of duties not according to different functions, but according to degrees of authority and corresponding responsibility is called ______', 'fill_in_blank', 'Scalar process', 'The scalar process establishes hierarchical authority relationships.'),
    (v_course_id, 'The flow of instructions or communications from the immediate superior to the top officer in an organisation is described as _________', 'fill_in_blank', 'Proper channel', 'Proper channel refers to the official communication pathway in an organization.'),
    (v_course_id, 'In Public administration, such activities in an organisation which aid the head of department or the chief executive in discharging his duties is known as _________', 'fill_in_blank', 'Staff', 'Staff functions support line executives in decision-making.'),
    (v_course_id, '_______ are the agencies which do not serve the public but the line agencies', 'fill_in_blank', 'Auxiliary agencies', 'Auxiliary agencies provide internal support services to other government agencies.'),
    (v_course_id, 'The traditional administrative organisation is called _________', 'fill_in_blank', 'Department', 'Departments are the fundamental units of traditional government organization.');

    -- Multiple choice questions (85% - 85 questions)
    INSERT INTO questions (course_id, question_text, question_type, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
    (v_course_id, 'One of the following is not a classification or type of Budget', 'multiple_choice', 'Performance budget', 'Program budget', 'Profit budget', 'Zero-based budget', 'C', 'Profit budget is not a standard classification of government budgeting systems.'),
    (v_course_id, 'The following are important principles of budget making except____________', 'multiple_choice', 'Budget should be balanced', 'Budget should be staggered', 'Budget should be comprehensive', 'Budget should be clear', 'B', 'Budget staggering is not a fundamental principle of budget making.'),
    (v_course_id, 'The advantages of delegated legislation exclude _________', 'multiple_choice', 'Saves parliamentary time', 'Interest of the people ignored', 'Allows for flexibility', 'Utilizes expert knowledge', 'B', 'Ignoring public interest is a disadvantage, not advantage, of delegated legislation.'),
    (v_course_id, '_____ is not among the major criticisms against Dicey''s interpretation of administrative law', 'multiple_choice', 'Universality of administrative law', 'Ignored existence of administrative law', 'Misinterpreted French droit administratif', 'Over-emphasized rule of law', 'A', 'Universality of administrative law was not a criticism of Dicey''s work.'),
    (v_course_id, 'A renowned scholar in administrative law is _________', 'multiple_choice', 'Max Weber', 'Ivor Jennings', 'Woodrow Wilson', 'Frederick Taylor', 'B', 'Ivor Jennings was a prominent scholar in administrative law.'),
    (v_course_id, 'The functions of O and M do not include _______', 'multiple_choice', 'Work simplification', 'Forms control', 'Industrialization', 'Office layout', 'C', 'Industrialization is not a function of Organization and Methods units.'),
    (v_course_id, 'The main defects of procedures include all but _______________', 'multiple_choice', 'Red tape', 'Bottlenecks', 'Efficiency', 'Duplication of work', 'C', 'Efficiency is a positive attribute, not a defect of procedures.'),
    (v_course_id, 'The legal rights of public employees includes the following with the exception of _____', 'multiple_choice', 'Right to embezzlement', 'Right to salary', 'Right to pension', 'Right to association', 'A', 'Embezzlement is illegal and not a right of public employees.'),
    (v_course_id, '_____ is not among the objectives of public employee union', 'multiple_choice', 'To take over administration', 'Better working conditions', 'Higher wages', 'Job security', 'A', 'Taking over administration is not an objective of public employee unions.'),
    (v_course_id, 'The obstacles to good public relations exclude _______', 'multiple_choice', 'Cordiality', 'Bureaucratic rigidity', 'Lack of funds', 'Poor communication', 'A', 'Cordiality promotes, rather than obstructs, good public relations.'),
    (v_course_id, '____ is not among the techniques of ascertaining public opinion', 'multiple_choice', 'Public opinion polls', 'Motivation', 'Interviews', 'Questionnaires', 'B', 'Motivation is not a technique for measuring public opinion.'),
    (v_course_id, 'The principles of promotion does not include', 'multiple_choice', 'Merit', 'Seniority', 'Confrontation', 'Fitness', 'C', 'Confrontation is not a principle used in promotion decisions.'),
    (v_course_id, 'Strictly speaking, ______ does not belong to the formal training', 'multiple_choice', 'Parental Training', 'Orientation training', 'In-service training', 'Foundation training', 'A', 'Parental training is informal, not formal organizational training.'),
    (v_course_id, 'The following are advantages of the merit system exclude _____', 'multiple_choice', 'Ensures efficiency', 'It leads public administration to the morass of political intrigues', 'Ensures continuity', 'Attracts best talents', 'B', 'Leading to political intrigues is a disadvantage, not advantage, of merit system.'),
    (v_course_id, 'The defects of spoils system exclude ____', 'multiple_choice', 'Inefficiency', 'Corruption', 'Motivates the employees', 'Instability', 'C', 'Employee motivation is not typically associated with the spoils system.'),
    (v_course_id, 'The foundation of personnel system includes all but _________', 'multiple_choice', 'Spoils system', 'Merit system', 'Career system', 'Position classification', 'A', 'The spoils system is not considered a foundation of modern personnel systems.'),
    (v_course_id, '_____ is not among the essential characteristics of bureaucracy', 'multiple_choice', 'Hierarchy', 'Personification of office in the incumbent', 'Division of labor', 'Written documents', 'B', 'Bureaucracy emphasizes impersonal offices, not personification in incumbents.'),
    (v_course_id, 'The German sociologist that popularized the study of bureaucracy is _________', 'multiple_choice', 'Karl Marx', 'Max Weber', 'Emile Durkheim', 'Georg Hegel', 'B', 'Max Weber is the seminal theorist on bureaucracy.'),
    (v_course_id, 'The problems of public corporation exclude_______', 'multiple_choice', 'Political interference', 'The problem of precondition', 'Financial constraints', 'Managerial inefficiency', 'B', 'Problem of precondition is not a commonly cited issue for public corporations.'),
    (v_course_id, '_____ is not a feature of public corporation', 'multiple_choice', 'Corporate personality', 'Profit – oriented', 'Service motive', 'Government ownership', 'B', 'Public corporations are service-oriented, not primarily profit-oriented.'),
    (v_course_id, 'One of the following is not a type of public corporation in Nigeria.', 'multiple_choice', 'Nigerian Railway Corporation', 'Federal Character Commission', 'Nigerian Ports Authority', 'Power Holding Company', 'B', 'Federal Character Commission is a constitutional body, not a public corporation.'),
    (v_course_id, 'The following reasons justify government participation in economic activities except________', 'multiple_choice', 'Need to plunder the economy', 'Provision of essential services', 'National security', 'Economic development', 'A', 'Plundering the economy is not a legitimate justification for government participation.'),
    (v_course_id, '______ is not among the types of public enterprises based on the ownership.', 'multiple_choice', 'Departmental undertaking', 'Public corporation', 'Amnesty', 'Government company', 'C', 'Amnesty is not a type of public enterprise based on ownership.'),
    (v_course_id, 'Factors necessitating centralization and decentralization exclude ________', 'multiple_choice', 'Size of organization', 'Nature of service', 'Absence of managers', 'Geographical area', 'C', 'Absence of managers is not a factor in centralization/decentralization decisions.'),
    (v_course_id, 'Advantages of a centralized system does not include _____', 'multiple_choice', 'Uniformity of action', 'It lacks flexibility of approach', 'Economies of scale', 'Better coordination', 'B', 'Lack of flexibility is a disadvantage, not advantage, of centralization.'),
    (v_course_id, 'All except one of the following are the disadvantages of a centralized system.', 'multiple_choice', 'It makes administrative abuses difficult', 'Delay in decision making', 'Overburdening of top executives', 'Kills initiative at lower levels', 'A', 'Making administrative abuses difficult is an advantage, not disadvantage.'),
    (v_course_id, 'The bureau type runs the following risks except ________', 'multiple_choice', 'The head may develop expertise', 'Abuse of power', 'Over-centralization', 'Succession problem', 'A', 'Developing expertise is positive, not a risk of bureau organization.'),
    (v_course_id, 'The disadvantages of Board type do not include _____', 'multiple_choice', 'Delay in decision making', 'The single head is necessary in a disciplined activities', 'Lack of clear responsibility', 'Compromise decisions', 'B', 'Need for single head in disciplined activities is not a disadvantage of boards.'),
    (v_course_id, '_____ is not a type of Board or Commission', 'multiple_choice', 'Advisory board', 'Executive board', 'Revenue board', 'Judicial board', 'C', 'Revenue board is not a standard classification of board types.'),
    (v_course_id, 'The four principles or bases on which a department is organized exclude ______', 'multiple_choice', 'Purpose', 'Process', 'Rotational principle', 'Clientele', 'C', 'Rotational principle is not a basis for departmental organization.'),
    (v_course_id, 'The functions of Auxiliary Agencies exclude ____________', 'multiple_choice', 'Provide common services', 'Encroaches upon the responsibilities of his agencies', 'Ensure economy', 'Maintain standards', 'B', 'Encroaching on other agencies responsibilities is not a function of auxiliary agencies.'),
    (v_course_id, '______ is not among the functions of staff agencies.', 'multiple_choice', 'Decision making', 'Advice', 'Planning', 'Research', 'A', 'Staff agencies advise but do not make final decisions.'),
    (v_course_id, 'The following are factors determining the degree of span of control except _______', 'multiple_choice', 'Nature of work', 'Ability of supervisor', 'Lack of consensus', 'Geographical dispersion', 'C', 'Lack of consensus is not a factor in determining span of control.'),
    (v_course_id, 'The bases of organization exclude ________', 'multiple_choice', 'Division of labor', 'Public relations', 'Hierarchy', 'Coordination', 'B', 'Public relations is a function, not a base of organization structure.'),
    (v_course_id, 'The following are the characteristics of organization except ________', 'multiple_choice', 'Division of labor', 'Profit maximization', 'Hierarchy', 'Coordination', 'B', 'Profit maximization is not a characteristic of public organizations.'),
    (v_course_id, 'The foundations of the modern personnel system include all except ________', 'multiple_choice', 'Merit system', 'Spoils system', 'Position classification', 'Career service', 'B', 'The spoils system is antithetical to modern personnel systems.'),
    (v_course_id, 'The Pendleton Act was passed by the United States Congress in the year ______', 'multiple_choice', '1883', '1901', '1923', '1945', 'A', 'The Pendleton Act was passed in 1883, establishing the US civil service.'),
    (v_course_id, 'The Act that gave the civil service permanency of tenure and its present character is known as ___', 'multiple_choice', 'Sherman Act', 'Pendleton Act', 'Hatch Act', 'Civil Rights Act', 'B', 'The Pendleton Act established the modern US civil service system.'),
    (v_course_id, 'Such a method of recruitment aimed at providing equality of opportunities to all to compete in open market public service is known as ______', 'multiple_choice', 'Spoils system', 'Merit system', 'Quota system', 'Patronage system', 'B', 'The merit system emphasizes equal opportunity based on qualifications.'),
    (v_course_id, '_____ is not among categories of training in an organization', 'multiple_choice', 'Induction training', 'Disengagement Training', 'In-service training', 'Refresher training', 'B', 'Disengagement training is not a standard category of organizational training.'),
    (v_course_id, 'An organisation aimed at achieving a public purpose authorized by law is known as _____', 'multiple_choice', 'Private corporation', 'Government corporation', 'Multinational corporation', 'Non-profit organization', 'B', 'Government corporations are established by law for public purposes.'),
    (v_course_id, 'The main characteristics of a government company include all except _____', 'multiple_choice', 'Separate legal entity', 'It is welfare – oriented', 'Commercial operations', 'Government ownership', 'B', 'Government companies can be commercially oriented, not necessarily welfare-oriented.'),
    (v_course_id, 'The grading of duties according to degrees of authority and corresponding responsibility in organisation is known as _______', 'multiple_choice', 'Division of labor', 'The scalar process', 'Coordination', 'Delegation', 'B', 'The scalar process establishes hierarchical authority relationships.'),
    (v_course_id, 'The line agencies do not perform one of the following functions.', 'multiple_choice', 'Policy implementation', 'Repressing workers', 'Service delivery', 'Program execution', 'B', 'Worker repression is not a legitimate function of line agencies.'),
    (v_course_id, 'According to Mooney, staff functions do not include _______', 'multiple_choice', 'Advice', 'Budgeting', 'Planning', 'Research', 'B', 'Budgeting is typically a line or auxiliary function, not purely staff.'),
    (v_course_id, '____ is not among the kinds of independent establishments', 'multiple_choice', 'Regulatory commissions', 'Information services', 'Government corporations', 'Advisory bodies', 'B', 'Information services are usually part of departments, not independent establishments.'),
    (v_course_id, 'The Bureau Type of Organisation is bedevilled by the following defects except ____', 'multiple_choice', 'Autocratic leadership', 'It eliminates partisan politics', 'Over-centralization', 'Succession problems', 'B', 'Eliminating partisan politics is positive, not a defect of bureau organization.'),
    (v_course_id, '_____ is not among the techniques of ascertaining public opinion', 'multiple_choice', 'The Judiciary', 'Public opinion polls', 'Mass media analysis', 'Public hearings', 'A', 'The judiciary does not typically ascertain public opinion.'),
    (v_course_id, 'In a broader sense of institutional process, the term O and M refers to ________', 'multiple_choice', 'Organization and Management', 'Operations and Maintenance', 'Output and Measurement', 'Oversight and Monitoring', 'A', 'O and M stands for Organization and Methods in public administration.'),
    (v_course_id, '______ is not a notable scholar in Administrative Law?', 'multiple_choice', 'Ivor Jennings', 'Max Weber', 'A. V. Dicey', 'F. J. Port', 'B', 'Max Weber is known for bureaucracy theory, not administrative law.');

    -- Additional fill in the blank questions to complete the set
    INSERT INTO questions (course_id, question_text, question_type, correct_answer, explanation) VALUES
    (v_course_id, 'At the federal level in Nigeria, the political head of every department is known as _________', 'fill_in_blank', 'Minister', 'Ministers are the political heads of federal departments in Nigeria.'),
    (v_course_id, 'A group of members who are required to act collectively upon all matters falling within their jurisdiction is called ______', 'fill_in_blank', 'Board', 'Boards make collective decisions on matters within their jurisdiction.'),
    (v_course_id, 'An organisation which has the leadership of the department in one person is called _________', 'fill_in_blank', 'Bureau type of organisation', 'Bureau organization features single-person leadership.'),
    (v_course_id, '_______ refers to where decision making authority is vested in the top level to which all matters pertaining to a particular problem are channelled.', 'fill_in_blank', 'Centralized organisation', 'Centralized organizations concentrate decision-making at the top.'),
    (v_course_id, 'The dispersal of authority among a number of individuals or units is referred to as _________', 'fill_in_blank', 'Decentralization', 'Decentralization distributes authority to lower levels or units.'),
    (v_course_id, 'An agency of the government through which the government manages its commercial and economic activities is known as _______', 'fill_in_blank', 'Public enterprise', 'Public enterprises conduct government commercial activities.'),
    (v_course_id, 'An enterprise established under the ordinary company law of the country in which the government has a commanding interest through its ownership of all or some of the shares is known as __________', 'fill_in_blank', 'State company', 'State companies are government-owned entities registered under company law.'),
    (v_course_id, 'A public corporation is constituted largely for ________', 'fill_in_blank', 'Public benefit', 'Public corporations are established primarily for public benefit.'),
    (v_course_id, 'The essence of a company is maximization of', 'fill_in_blank', 'Profit', 'Private companies primarily aim for profit maximization.'),
    (v_course_id, 'A personnel system where the employees are classified into a hierarchical sections, divisions, etc is describes as ___________ system', 'fill_in_blank', 'Bureaucratic', 'Bureaucratic systems feature hierarchical classification of personnel.'),
    (v_course_id, 'A system where a distinction is made between different grades of personnel and promotion from lower to the higher grade is strictly restricted is called _______', 'fill_in_blank', 'Aristocratic system', 'Aristocratic systems restrict mobility between personnel grades.'),
    (v_course_id, 'A system in which no man has any more intrinsic right to official station than another is known as ______', 'fill_in_blank', 'Democratic system', 'Democratic systems emphasize equality of opportunity in public service.'),
    (v_course_id, 'The German sociologist that gave a systematic analysis of bureaucracy is ______', 'fill_in_blank', 'Max Weber', 'Max Weber developed the classic theory of bureaucracy.'),
    (v_course_id, 'In public administration, the grouping together of posts into various classes on the basis of their respective duties and responsibilities is known as ____________', 'fill_in_blank', 'Classification', 'Position classification groups jobs by duties and responsibilities.'),
    (v_course_id, 'According to Waldo, __________ is the prescribed or customary way of working together with the conduct of an organisation''s business.', 'fill_in_blank', 'Procedure', 'Procedures are established ways of conducting organizational business.');

END $$;